// Code generated by MockGen. DO NOT EDIT.
// Source: ./interface.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	auth_methods "github.com/rmorlok/authproxy/internal/auth_methods"
	iface "github.com/rmorlok/authproxy/internal/core/iface"
	connectors "github.com/rmorlok/authproxy/internal/schema/resources/connectors"
)

// MockFactory is a mock of Factory interface.
type MockFactory struct {
	ctrl     *gomock.Controller
	recorder *MockFactoryMockRecorder
}

// MockFactoryMockRecorder is the mock recorder for MockFactory.
type MockFactoryMockRecorder struct {
	mock *MockFactory
}

// NewMockFactory creates a new mock instance.
func NewMockFactory(ctrl *gomock.Controller) *MockFactory {
	mock := &MockFactory{ctrl: ctrl}
	mock.recorder = &MockFactoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFactory) EXPECT() *MockFactoryMockRecorder {
	return m.recorder
}

// NewAuthenticator mocks base method.
func (m *MockFactory) NewAuthenticator(connection iface.Connection) auth_methods.Authenticator {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewAuthenticator", connection)
	ret0, _ := ret[0].(auth_methods.Authenticator)
	return ret0
}

// NewAuthenticator indicates an expected call of NewAuthenticator.
func (mr *MockFactoryMockRecorder) NewAuthenticator(connection interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewAuthenticator", reflect.TypeOf((*MockFactory)(nil).NewAuthenticator), connection)
}

// PersistCredentials mocks base method.
func (m *MockFactory) PersistCredentials(ctx context.Context, connection iface.Connection, placement *connectors.ApiKeyPlacement, credData map[string]any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PersistCredentials", ctx, connection, placement, credData)
	ret0, _ := ret[0].(error)
	return ret0
}

// PersistCredentials indicates an expected call of PersistCredentials.
func (mr *MockFactoryMockRecorder) PersistCredentials(ctx, connection, placement, credData interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PersistCredentials", reflect.TypeOf((*MockFactory)(nil).PersistCredentials), ctx, connection, placement, credData)
}
