// Code generated by MockGen. DO NOT EDIT.
// Source: ./interface.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	http "net/http"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	iface "github.com/rmorlok/authproxy/core/iface"
	request_log "github.com/rmorlok/authproxy/request_log"
)

// MockNoAuthConnection is a mock of NoAuthConnection interface.
type MockNoAuthConnection struct {
	ctrl     *gomock.Controller
	recorder *MockNoAuthConnectionMockRecorder
}

// MockNoAuthConnectionMockRecorder is the mock recorder for MockNoAuthConnection.
type MockNoAuthConnectionMockRecorder struct {
	mock *MockNoAuthConnection
}

// NewMockNoAuthConnection creates a new mock instance.
func NewMockNoAuthConnection(ctrl *gomock.Controller) *MockNoAuthConnection {
	mock := &MockNoAuthConnection{ctrl: ctrl}
	mock.recorder = &MockNoAuthConnectionMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNoAuthConnection) EXPECT() *MockNoAuthConnectionMockRecorder {
	return m.recorder
}

// ProxyRequest mocks base method.
func (m *MockNoAuthConnection) ProxyRequest(ctx context.Context, reqType request_log.RequestType, req *iface.ProxyRequest) (*iface.ProxyResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProxyRequest", ctx, reqType, req)
	ret0, _ := ret[0].(*iface.ProxyResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ProxyRequest indicates an expected call of ProxyRequest.
func (mr *MockNoAuthConnectionMockRecorder) ProxyRequest(ctx, reqType, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProxyRequest", reflect.TypeOf((*MockNoAuthConnection)(nil).ProxyRequest), ctx, reqType, req)
}

// ProxyRequestRaw mocks base method.
func (m *MockNoAuthConnection) ProxyRequestRaw(ctx context.Context, reqType request_log.RequestType, req *iface.ProxyRequest, w http.ResponseWriter) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProxyRequestRaw", ctx, reqType, req, w)
	ret0, _ := ret[0].(error)
	return ret0
}

// ProxyRequestRaw indicates an expected call of ProxyRequestRaw.
func (mr *MockNoAuthConnectionMockRecorder) ProxyRequestRaw(ctx, reqType, req, w interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProxyRequestRaw", reflect.TypeOf((*MockNoAuthConnection)(nil).ProxyRequestRaw), ctx, reqType, req, w)
}
