apiVersion: authproxy.net/v1alpha1
kind: Connector
metadata:
  name: api-key-header
  labels:
    type: openweathermap
spec:
  definition:
    displayName: OpenWeatherMap
    logo:
      publicUrl: https://example.com/owm.png
    description: 'Weather data via OpenWeatherMap.

'
    auth:
      type: api-key
      placement:
        type: header
        headerName: X-API-Key
        prefix: ''
