// Code generated by MockGen. DO NOT EDIT.
// Source: ./interface.go

// Package mock is a generated GoMock package.
package mock

import (
	http "net/http"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	apid "github.com/rmorlok/authproxy/internal/apid"
	httpf "github.com/rmorlok/authproxy/internal/httpf"
	common "github.com/rmorlok/authproxy/internal/schema/common"
	connectors "github.com/rmorlok/authproxy/internal/schema/resources/connectors"
	gentleman "gopkg.in/h2non/gentleman.v2"
)

// MockConnectorGeneration is a mock of ConnectorGeneration interface.
type MockConnectorGeneration struct {
	ctrl     *gomock.Controller
	recorder *MockConnectorGenerationMockRecorder
}

// MockConnectorGenerationMockRecorder is the mock recorder for MockConnectorGeneration.
type MockConnectorGenerationMockRecorder struct {
	mock *MockConnectorGeneration
}

// NewMockConnectorGeneration creates a new mock instance.
func NewMockConnectorGeneration(ctrl *gomock.Controller) *MockConnectorGeneration {
	mock := &MockConnectorGeneration{ctrl: ctrl}
	mock.recorder = &MockConnectorGenerationMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConnectorGeneration) EXPECT() *MockConnectorGenerationMockRecorder {
	return m.recorder
}

// GetGeneration mocks base method.
func (m *MockConnectorGeneration) GetGeneration() uint64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGeneration")
	ret0, _ := ret[0].(uint64)
	return ret0
}

// GetGeneration indicates an expected call of GetGeneration.
func (mr *MockConnectorGenerationMockRecorder) GetGeneration() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGeneration", reflect.TypeOf((*MockConnectorGeneration)(nil).GetGeneration))
}

// GetId mocks base method.
func (m *MockConnectorGeneration) GetId() apid.ID {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetId")
	ret0, _ := ret[0].(apid.ID)
	return ret0
}

// GetId indicates an expected call of GetId.
func (mr *MockConnectorGenerationMockRecorder) GetId() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetId", reflect.TypeOf((*MockConnectorGeneration)(nil).GetId))
}

// GetNamespace mocks base method.
func (m *MockConnectorGeneration) GetNamespace() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNamespace")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetNamespace indicates an expected call of GetNamespace.
func (mr *MockConnectorGenerationMockRecorder) GetNamespace() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNamespace", reflect.TypeOf((*MockConnectorGeneration)(nil).GetNamespace))
}

// MockGettableConnectorGeneration is a mock of GettableConnectorGeneration interface.
type MockGettableConnectorGeneration struct {
	ctrl     *gomock.Controller
	recorder *MockGettableConnectorGenerationMockRecorder
}

// MockGettableConnectorGenerationMockRecorder is the mock recorder for MockGettableConnectorGeneration.
type MockGettableConnectorGenerationMockRecorder struct {
	mock *MockGettableConnectorGeneration
}

// NewMockGettableConnectorGeneration creates a new mock instance.
func NewMockGettableConnectorGeneration(ctrl *gomock.Controller) *MockGettableConnectorGeneration {
	mock := &MockGettableConnectorGeneration{ctrl: ctrl}
	mock.recorder = &MockGettableConnectorGenerationMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGettableConnectorGeneration) EXPECT() *MockGettableConnectorGenerationMockRecorder {
	return m.recorder
}

// GetConnector mocks base method.
func (m *MockGettableConnectorGeneration) GetConnector() httpf.ConnectorGeneration {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetConnector")
	ret0, _ := ret[0].(httpf.ConnectorGeneration)
	return ret0
}

// GetConnector indicates an expected call of GetConnector.
func (mr *MockGettableConnectorGenerationMockRecorder) GetConnector() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConnector", reflect.TypeOf((*MockGettableConnectorGeneration)(nil).GetConnector))
}

// MockRateLimitConfigProvider is a mock of RateLimitConfigProvider interface.
type MockRateLimitConfigProvider struct {
	ctrl     *gomock.Controller
	recorder *MockRateLimitConfigProviderMockRecorder
}

// MockRateLimitConfigProviderMockRecorder is the mock recorder for MockRateLimitConfigProvider.
type MockRateLimitConfigProviderMockRecorder struct {
	mock *MockRateLimitConfigProvider
}

// NewMockRateLimitConfigProvider creates a new mock instance.
func NewMockRateLimitConfigProvider(ctrl *gomock.Controller) *MockRateLimitConfigProvider {
	mock := &MockRateLimitConfigProvider{ctrl: ctrl}
	mock.recorder = &MockRateLimitConfigProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRateLimitConfigProvider) EXPECT() *MockRateLimitConfigProviderMockRecorder {
	return m.recorder
}

// GetRateLimitConfig mocks base method.
func (m *MockRateLimitConfigProvider) GetRateLimitConfig() *connectors.RateLimiting {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRateLimitConfig")
	ret0, _ := ret[0].(*connectors.RateLimiting)
	return ret0
}

// GetRateLimitConfig indicates an expected call of GetRateLimitConfig.
func (mr *MockRateLimitConfigProviderMockRecorder) GetRateLimitConfig() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRateLimitConfig", reflect.TypeOf((*MockRateLimitConfigProvider)(nil).GetRateLimitConfig))
}

// MockTracePropagationProvider is a mock of TracePropagationProvider interface.
type MockTracePropagationProvider struct {
	ctrl     *gomock.Controller
	recorder *MockTracePropagationProviderMockRecorder
}

// MockTracePropagationProviderMockRecorder is the mock recorder for MockTracePropagationProvider.
type MockTracePropagationProviderMockRecorder struct {
	mock *MockTracePropagationProvider
}

// NewMockTracePropagationProvider creates a new mock instance.
func NewMockTracePropagationProvider(ctrl *gomock.Controller) *MockTracePropagationProvider {
	mock := &MockTracePropagationProvider{ctrl: ctrl}
	mock.recorder = &MockTracePropagationProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTracePropagationProvider) EXPECT() *MockTracePropagationProviderMockRecorder {
	return m.recorder
}

// PropagateTraceContext mocks base method.
func (m *MockTracePropagationProvider) PropagateTraceContext() *bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PropagateTraceContext")
	ret0, _ := ret[0].(*bool)
	return ret0
}

// PropagateTraceContext indicates an expected call of PropagateTraceContext.
func (mr *MockTracePropagationProviderMockRecorder) PropagateTraceContext() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PropagateTraceContext", reflect.TypeOf((*MockTracePropagationProvider)(nil).PropagateTraceContext))
}

// MockConnection is a mock of Connection interface.
type MockConnection struct {
	ctrl     *gomock.Controller
	recorder *MockConnectionMockRecorder
}

// MockConnectionMockRecorder is the mock recorder for MockConnection.
type MockConnectionMockRecorder struct {
	mock *MockConnection
}

// NewMockConnection creates a new mock instance.
func NewMockConnection(ctrl *gomock.Controller) *MockConnection {
	mock := &MockConnection{ctrl: ctrl}
	mock.recorder = &MockConnectionMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConnection) EXPECT() *MockConnectionMockRecorder {
	return m.recorder
}

// GetConnectorGeneration mocks base method.
func (m *MockConnection) GetConnectorGeneration() uint64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetConnectorGeneration")
	ret0, _ := ret[0].(uint64)
	return ret0
}

// GetConnectorGeneration indicates an expected call of GetConnectorGeneration.
func (mr *MockConnectionMockRecorder) GetConnectorGeneration() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConnectorGeneration", reflect.TypeOf((*MockConnection)(nil).GetConnectorGeneration))
}

// GetConnectorId mocks base method.
func (m *MockConnection) GetConnectorId() apid.ID {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetConnectorId")
	ret0, _ := ret[0].(apid.ID)
	return ret0
}

// GetConnectorId indicates an expected call of GetConnectorId.
func (mr *MockConnectionMockRecorder) GetConnectorId() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConnectorId", reflect.TypeOf((*MockConnection)(nil).GetConnectorId))
}

// GetId mocks base method.
func (m *MockConnection) GetId() apid.ID {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetId")
	ret0, _ := ret[0].(apid.ID)
	return ret0
}

// GetId indicates an expected call of GetId.
func (mr *MockConnectionMockRecorder) GetId() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetId", reflect.TypeOf((*MockConnection)(nil).GetId))
}

// GetLabels mocks base method.
func (m *MockConnection) GetLabels() map[string]string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLabels")
	ret0, _ := ret[0].(map[string]string)
	return ret0
}

// GetLabels indicates an expected call of GetLabels.
func (mr *MockConnectionMockRecorder) GetLabels() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLabels", reflect.TypeOf((*MockConnection)(nil).GetLabels))
}

// GetNamespace mocks base method.
func (m *MockConnection) GetNamespace() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNamespace")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetNamespace indicates an expected call of GetNamespace.
func (mr *MockConnectionMockRecorder) GetNamespace() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNamespace", reflect.TypeOf((*MockConnection)(nil).GetNamespace))
}

// MockActor is a mock of Actor interface.
type MockActor struct {
	ctrl     *gomock.Controller
	recorder *MockActorMockRecorder
}

// MockActorMockRecorder is the mock recorder for MockActor.
type MockActorMockRecorder struct {
	mock *MockActor
}

// NewMockActor creates a new mock instance.
func NewMockActor(ctrl *gomock.Controller) *MockActor {
	mock := &MockActor{ctrl: ctrl}
	mock.recorder = &MockActorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockActor) EXPECT() *MockActorMockRecorder {
	return m.recorder
}

// GetId mocks base method.
func (m *MockActor) GetId() apid.ID {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetId")
	ret0, _ := ret[0].(apid.ID)
	return ret0
}

// GetId indicates an expected call of GetId.
func (mr *MockActorMockRecorder) GetId() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetId", reflect.TypeOf((*MockActor)(nil).GetId))
}

// GetLabels mocks base method.
func (m *MockActor) GetLabels() map[string]string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLabels")
	ret0, _ := ret[0].(map[string]string)
	return ret0
}

// GetLabels indicates an expected call of GetLabels.
func (mr *MockActorMockRecorder) GetLabels() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLabels", reflect.TypeOf((*MockActor)(nil).GetLabels))
}

// GetName mocks base method.
func (m *MockActor) GetName() common.ResourceName {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetName")
	ret0, _ := ret[0].(common.ResourceName)
	return ret0
}

// GetName indicates an expected call of GetName.
func (mr *MockActorMockRecorder) GetName() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetName", reflect.TypeOf((*MockActor)(nil).GetName))
}

// GetNamespace mocks base method.
func (m *MockActor) GetNamespace() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNamespace")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetNamespace indicates an expected call of GetNamespace.
func (mr *MockActorMockRecorder) GetNamespace() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNamespace", reflect.TypeOf((*MockActor)(nil).GetNamespace))
}

// MockF is a mock of F interface.
type MockF struct {
	ctrl     *gomock.Controller
	recorder *MockFMockRecorder
}

// MockFMockRecorder is the mock recorder for MockF.
type MockFMockRecorder struct {
	mock *MockF
}

// NewMockF creates a new mock instance.
func NewMockF(ctrl *gomock.Controller) *MockF {
	mock := &MockF{ctrl: ctrl}
	mock.recorder = &MockFMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockF) EXPECT() *MockFMockRecorder {
	return m.recorder
}

// ForActor mocks base method.
func (m *MockF) ForActor(actor httpf.Actor) httpf.F {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ForActor", actor)
	ret0, _ := ret[0].(httpf.F)
	return ret0
}

// ForActor indicates an expected call of ForActor.
func (mr *MockFMockRecorder) ForActor(actor interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ForActor", reflect.TypeOf((*MockF)(nil).ForActor), actor)
}

// ForConnection mocks base method.
func (m *MockF) ForConnection(cv httpf.Connection) httpf.F {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ForConnection", cv)
	ret0, _ := ret[0].(httpf.F)
	return ret0
}

// ForConnection indicates an expected call of ForConnection.
func (mr *MockFMockRecorder) ForConnection(cv interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ForConnection", reflect.TypeOf((*MockF)(nil).ForConnection), cv)
}

// ForConnectorGeneration mocks base method.
func (m *MockF) ForConnectorGeneration(cv httpf.ConnectorGeneration) httpf.F {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ForConnectorGeneration", cv)
	ret0, _ := ret[0].(httpf.F)
	return ret0
}

// ForConnectorGeneration indicates an expected call of ForConnectorGeneration.
func (mr *MockFMockRecorder) ForConnectorGeneration(cv interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ForConnectorGeneration", reflect.TypeOf((*MockF)(nil).ForConnectorGeneration), cv)
}

// ForLabels mocks base method.
func (m *MockF) ForLabels(labels map[string]string) httpf.F {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ForLabels", labels)
	ret0, _ := ret[0].(httpf.F)
	return ret0
}

// ForLabels indicates an expected call of ForLabels.
func (mr *MockFMockRecorder) ForLabels(labels interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ForLabels", reflect.TypeOf((*MockF)(nil).ForLabels), labels)
}

// ForRequestInfo mocks base method.
func (m *MockF) ForRequestInfo(ri httpf.RequestInfo) httpf.F {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ForRequestInfo", ri)
	ret0, _ := ret[0].(httpf.F)
	return ret0
}

// ForRequestInfo indicates an expected call of ForRequestInfo.
func (mr *MockFMockRecorder) ForRequestInfo(ri interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ForRequestInfo", reflect.TypeOf((*MockF)(nil).ForRequestInfo), ri)
}

// ForRequestType mocks base method.
func (m *MockF) ForRequestType(rt httpf.RequestType) httpf.F {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ForRequestType", rt)
	ret0, _ := ret[0].(httpf.F)
	return ret0
}

// ForRequestType indicates an expected call of ForRequestType.
func (mr *MockFMockRecorder) ForRequestType(rt interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ForRequestType", reflect.TypeOf((*MockF)(nil).ForRequestType), rt)
}

// New mocks base method.
func (m *MockF) New() *gentleman.Client {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "New")
	ret0, _ := ret[0].(*gentleman.Client)
	return ret0
}

// New indicates an expected call of New.
func (mr *MockFMockRecorder) New() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "New", reflect.TypeOf((*MockF)(nil).New))
}

// NewHTTPClient mocks base method.
func (m *MockF) NewHTTPClient() *http.Client {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewHTTPClient")
	ret0, _ := ret[0].(*http.Client)
	return ret0
}

// NewHTTPClient indicates an expected call of NewHTTPClient.
func (mr *MockFMockRecorder) NewHTTPClient() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewHTTPClient", reflect.TypeOf((*MockF)(nil).NewHTTPClient))
}
