// Code generated by MockGen. DO NOT EDIT.
// Source: ./authenticator.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	auth_methods "github.com/rmorlok/authproxy/internal/auth_methods"
)

// MockAuthenticator is a mock of Authenticator interface.
type MockAuthenticator struct {
	ctrl     *gomock.Controller
	recorder *MockAuthenticatorMockRecorder
}

// MockAuthenticatorMockRecorder is the mock recorder for MockAuthenticator.
type MockAuthenticatorMockRecorder struct {
	mock *MockAuthenticator
}

// NewMockAuthenticator creates a new mock instance.
func NewMockAuthenticator(ctrl *gomock.Controller) *MockAuthenticator {
	mock := &MockAuthenticator{ctrl: ctrl}
	mock.recorder = &MockAuthenticatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthenticator) EXPECT() *MockAuthenticatorMockRecorder {
	return m.recorder
}

// RecoverFrom401 mocks base method.
func (m *MockAuthenticator) RecoverFrom401(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecoverFrom401", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// RecoverFrom401 indicates an expected call of RecoverFrom401.
func (mr *MockAuthenticatorMockRecorder) RecoverFrom401(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecoverFrom401", reflect.TypeOf((*MockAuthenticator)(nil).RecoverFrom401), ctx)
}

// Resolve mocks base method.
func (m *MockAuthenticator) Resolve(ctx context.Context) (auth_methods.AuthApplication, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Resolve", ctx)
	ret0, _ := ret[0].(auth_methods.AuthApplication)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Resolve indicates an expected call of Resolve.
func (mr *MockAuthenticatorMockRecorder) Resolve(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Resolve", reflect.TypeOf((*MockAuthenticator)(nil).Resolve), ctx)
}

// Revoke mocks base method.
func (m *MockAuthenticator) Revoke(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Revoke", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Revoke indicates an expected call of Revoke.
func (mr *MockAuthenticatorMockRecorder) Revoke(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Revoke", reflect.TypeOf((*MockAuthenticator)(nil).Revoke), ctx)
}

// SupportsRevoke mocks base method.
func (m *MockAuthenticator) SupportsRevoke() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SupportsRevoke")
	ret0, _ := ret[0].(bool)
	return ret0
}

// SupportsRevoke indicates an expected call of SupportsRevoke.
func (mr *MockAuthenticatorMockRecorder) SupportsRevoke() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SupportsRevoke", reflect.TypeOf((*MockAuthenticator)(nil).SupportsRevoke))
}
