DROP INDEX IF EXISTS idx_app_metrics_request_events_rate_limit_id;
DROP INDEX IF EXISTS idx_app_metrics_request_events_response_source;

ALTER TABLE app_metrics_request_events DROP COLUMN rate_limit_matched;
ALTER TABLE app_metrics_request_events DROP COLUMN rate_limit_bucket;
ALTER TABLE app_metrics_request_events DROP COLUMN rate_limit_mode;
ALTER TABLE app_metrics_request_events DROP COLUMN rate_limit_id;
ALTER TABLE app_metrics_request_events DROP COLUMN response_source;
