// Code generated by MockGen. DO NOT EDIT.
// Source: ./interface.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	url "net/url"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	apid "github.com/rmorlok/authproxy/internal/apid"
	auth_methods "github.com/rmorlok/authproxy/internal/auth_methods"
	oauth2 "github.com/rmorlok/authproxy/internal/auth_methods/oauth2"
	iface "github.com/rmorlok/authproxy/internal/core/iface"
	auth "github.com/rmorlok/authproxy/internal/schema/auth"
	connectors "github.com/rmorlok/authproxy/internal/schema/resources/connectors"
)

// MockIActorData is a mock of IActorData interface.
type MockIActorData struct {
	ctrl     *gomock.Controller
	recorder *MockIActorDataMockRecorder
}

// MockIActorDataMockRecorder is the mock recorder for MockIActorData.
type MockIActorDataMockRecorder struct {
	mock *MockIActorData
}

// NewMockIActorData creates a new mock instance.
func NewMockIActorData(ctrl *gomock.Controller) *MockIActorData {
	mock := &MockIActorData{ctrl: ctrl}
	mock.recorder = &MockIActorDataMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIActorData) EXPECT() *MockIActorDataMockRecorder {
	return m.recorder
}

// GetExternalId mocks base method.
func (m *MockIActorData) GetExternalId() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetExternalId")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetExternalId indicates an expected call of GetExternalId.
func (mr *MockIActorDataMockRecorder) GetExternalId() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetExternalId", reflect.TypeOf((*MockIActorData)(nil).GetExternalId))
}

// GetId mocks base method.
func (m *MockIActorData) GetId() apid.ID {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetId")
	ret0, _ := ret[0].(apid.ID)
	return ret0
}

// GetId indicates an expected call of GetId.
func (mr *MockIActorDataMockRecorder) GetId() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetId", reflect.TypeOf((*MockIActorData)(nil).GetId))
}

// GetLabels mocks base method.
func (m *MockIActorData) GetLabels() map[string]string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLabels")
	ret0, _ := ret[0].(map[string]string)
	return ret0
}

// GetLabels indicates an expected call of GetLabels.
func (mr *MockIActorDataMockRecorder) GetLabels() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLabels", reflect.TypeOf((*MockIActorData)(nil).GetLabels))
}

// GetNamespace mocks base method.
func (m *MockIActorData) GetNamespace() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNamespace")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetNamespace indicates an expected call of GetNamespace.
func (mr *MockIActorDataMockRecorder) GetNamespace() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNamespace", reflect.TypeOf((*MockIActorData)(nil).GetNamespace))
}

// GetPermissions mocks base method.
func (m *MockIActorData) GetPermissions() []auth.Permission {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPermissions")
	ret0, _ := ret[0].([]auth.Permission)
	return ret0
}

// GetPermissions indicates an expected call of GetPermissions.
func (mr *MockIActorDataMockRecorder) GetPermissions() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPermissions", reflect.TypeOf((*MockIActorData)(nil).GetPermissions))
}

// MockFactory is a mock of Factory interface.
type MockFactory struct {
	ctrl     *gomock.Controller
	recorder *MockFactoryMockRecorder
}

// MockFactoryMockRecorder is the mock recorder for MockFactory.
type MockFactoryMockRecorder struct {
	mock *MockFactory
}

// NewMockFactory creates a new mock instance.
func NewMockFactory(ctrl *gomock.Controller) *MockFactory {
	mock := &MockFactory{ctrl: ctrl}
	mock.recorder = &MockFactoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFactory) EXPECT() *MockFactoryMockRecorder {
	return m.recorder
}

// GetOAuth2State mocks base method.
func (m *MockFactory) GetOAuth2State(ctx context.Context, actor oauth2.IActorData, stateId apid.ID) (oauth2.OAuth2Connection, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOAuth2State", ctx, actor, stateId)
	ret0, _ := ret[0].(oauth2.OAuth2Connection)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOAuth2State indicates an expected call of GetOAuth2State.
func (mr *MockFactoryMockRecorder) GetOAuth2State(ctx, actor, stateId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOAuth2State", reflect.TypeOf((*MockFactory)(nil).GetOAuth2State), ctx, actor, stateId)
}

// ManifestSetupSteps mocks base method.
func (m *MockFactory) ManifestSetupSteps(connection iface.Connection, connector *connectors.Connector) []iface.ManifestSetupStep {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ManifestSetupSteps", connection, connector)
	ret0, _ := ret[0].([]iface.ManifestSetupStep)
	return ret0
}

// ManifestSetupSteps indicates an expected call of ManifestSetupSteps.
func (mr *MockFactoryMockRecorder) ManifestSetupSteps(connection, connector interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ManifestSetupSteps", reflect.TypeOf((*MockFactory)(nil).ManifestSetupSteps), connection, connector)
}

// NewAuthenticator mocks base method.
func (m *MockFactory) NewAuthenticator(connection iface.Connection) auth_methods.Authenticator {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewAuthenticator", connection)
	ret0, _ := ret[0].(auth_methods.Authenticator)
	return ret0
}

// NewAuthenticator indicates an expected call of NewAuthenticator.
func (mr *MockFactoryMockRecorder) NewAuthenticator(connection interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewAuthenticator", reflect.TypeOf((*MockFactory)(nil).NewAuthenticator), connection)
}

// NewOAuth2 mocks base method.
func (m *MockFactory) NewOAuth2(connection iface.Connection) oauth2.OAuth2Connection {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewOAuth2", connection)
	ret0, _ := ret[0].(oauth2.OAuth2Connection)
	return ret0
}

// NewOAuth2 indicates an expected call of NewOAuth2.
func (mr *MockFactoryMockRecorder) NewOAuth2(connection interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewOAuth2", reflect.TypeOf((*MockFactory)(nil).NewOAuth2), connection)
}

// MockOAuth2Connection is a mock of OAuth2Connection interface.
type MockOAuth2Connection struct {
	ctrl     *gomock.Controller
	recorder *MockOAuth2ConnectionMockRecorder
}

// MockOAuth2ConnectionMockRecorder is the mock recorder for MockOAuth2Connection.
type MockOAuth2ConnectionMockRecorder struct {
	mock *MockOAuth2Connection
}

// NewMockOAuth2Connection creates a new mock instance.
func NewMockOAuth2Connection(ctrl *gomock.Controller) *MockOAuth2Connection {
	mock := &MockOAuth2Connection{ctrl: ctrl}
	mock.recorder = &MockOAuth2ConnectionMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOAuth2Connection) EXPECT() *MockOAuth2ConnectionMockRecorder {
	return m.recorder
}

// CallbackFrom3rdParty mocks base method.
func (m *MockOAuth2Connection) CallbackFrom3rdParty(ctx context.Context, query url.Values) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CallbackFrom3rdParty", ctx, query)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CallbackFrom3rdParty indicates an expected call of CallbackFrom3rdParty.
func (mr *MockOAuth2ConnectionMockRecorder) CallbackFrom3rdParty(ctx, query interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CallbackFrom3rdParty", reflect.TypeOf((*MockOAuth2Connection)(nil).CallbackFrom3rdParty), ctx, query)
}

// CancelSessionAfterAuth mocks base method.
func (m *MockOAuth2Connection) CancelSessionAfterAuth() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CancelSessionAfterAuth")
	ret0, _ := ret[0].(bool)
	return ret0
}

// CancelSessionAfterAuth indicates an expected call of CancelSessionAfterAuth.
func (mr *MockOAuth2ConnectionMockRecorder) CancelSessionAfterAuth() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CancelSessionAfterAuth", reflect.TypeOf((*MockOAuth2Connection)(nil).CancelSessionAfterAuth))
}

// ExchangeClientCredentials mocks base method.
func (m *MockOAuth2Connection) ExchangeClientCredentials(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExchangeClientCredentials", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// ExchangeClientCredentials indicates an expected call of ExchangeClientCredentials.
func (mr *MockOAuth2ConnectionMockRecorder) ExchangeClientCredentials(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExchangeClientCredentials", reflect.TypeOf((*MockOAuth2Connection)(nil).ExchangeClientCredentials), ctx)
}

// GenerateAuthUrl mocks base method.
func (m *MockOAuth2Connection) GenerateAuthUrl(ctx context.Context, actor oauth2.IActorData) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateAuthUrl", ctx, actor)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateAuthUrl indicates an expected call of GenerateAuthUrl.
func (mr *MockOAuth2ConnectionMockRecorder) GenerateAuthUrl(ctx, actor interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateAuthUrl", reflect.TypeOf((*MockOAuth2Connection)(nil).GenerateAuthUrl), ctx, actor)
}

// RecordCancelSessionAfterAuth mocks base method.
func (m *MockOAuth2Connection) RecordCancelSessionAfterAuth(ctx context.Context, shouldCancel bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecordCancelSessionAfterAuth", ctx, shouldCancel)
	ret0, _ := ret[0].(error)
	return ret0
}

// RecordCancelSessionAfterAuth indicates an expected call of RecordCancelSessionAfterAuth.
func (mr *MockOAuth2ConnectionMockRecorder) RecordCancelSessionAfterAuth(ctx, shouldCancel interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordCancelSessionAfterAuth", reflect.TypeOf((*MockOAuth2Connection)(nil).RecordCancelSessionAfterAuth), ctx, shouldCancel)
}

// SetStateAndGeneratePublicUrl mocks base method.
func (m *MockOAuth2Connection) SetStateAndGeneratePublicUrl(ctx context.Context, actor oauth2.IActorData, returnToUrl string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetStateAndGeneratePublicUrl", ctx, actor, returnToUrl)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetStateAndGeneratePublicUrl indicates an expected call of SetStateAndGeneratePublicUrl.
func (mr *MockOAuth2ConnectionMockRecorder) SetStateAndGeneratePublicUrl(ctx, actor, returnToUrl interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetStateAndGeneratePublicUrl", reflect.TypeOf((*MockOAuth2Connection)(nil).SetStateAndGeneratePublicUrl), ctx, actor, returnToUrl)
}
