{{- $ports := (include "authproxy.enabledPorts" . | fromYaml).ports -}}
{{- if $ports -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "authproxy.fullname" . }}
  labels:
    {{- include "authproxy.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "authproxy.selectorLabels" . | nindent 4 }}
  ports:
    {{- range $ports }}
    - name: {{ .name }}
      port: {{ .port }}
      targetPort: {{ .name }}
      protocol: TCP
    {{- end }}
{{- end }}
