// Code generated by MockGen. DO NOT EDIT.
// Source: ./interface.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	apid "github.com/rmorlok/authproxy/internal/apid"
	app_metrics "github.com/rmorlok/authproxy/internal/app_metrics"
)

// MockLogRetriever is a mock of LogRetriever interface.
type MockLogRetriever struct {
	ctrl     *gomock.Controller
	recorder *MockLogRetrieverMockRecorder
}

// MockLogRetrieverMockRecorder is the mock recorder for MockLogRetriever.
type MockLogRetrieverMockRecorder struct {
	mock *MockLogRetriever
}

// NewMockLogRetriever creates a new mock instance.
func NewMockLogRetriever(ctrl *gomock.Controller) *MockLogRetriever {
	mock := &MockLogRetriever{ctrl: ctrl}
	mock.recorder = &MockLogRetrieverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLogRetriever) EXPECT() *MockLogRetrieverMockRecorder {
	return m.recorder
}

// GetFullLog mocks base method.
func (m *MockLogRetriever) GetFullLog(ctx context.Context, id apid.ID) (*app_metrics.FullLog, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFullLog", ctx, id)
	ret0, _ := ret[0].(*app_metrics.FullLog)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFullLog indicates an expected call of GetFullLog.
func (mr *MockLogRetrieverMockRecorder) GetFullLog(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFullLog", reflect.TypeOf((*MockLogRetriever)(nil).GetFullLog), ctx, id)
}

// ListRequestsFromCursor mocks base method.
func (m *MockLogRetriever) ListRequestsFromCursor(ctx context.Context, cursor string) (app_metrics.ListRequestExecutor, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListRequestsFromCursor", ctx, cursor)
	ret0, _ := ret[0].(app_metrics.ListRequestExecutor)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListRequestsFromCursor indicates an expected call of ListRequestsFromCursor.
func (mr *MockLogRetrieverMockRecorder) ListRequestsFromCursor(ctx, cursor interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListRequestsFromCursor", reflect.TypeOf((*MockLogRetriever)(nil).ListRequestsFromCursor), ctx, cursor)
}

// NewListRequestsBuilder mocks base method.
func (m *MockLogRetriever) NewListRequestsBuilder() app_metrics.ListRequestBuilder {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewListRequestsBuilder")
	ret0, _ := ret[0].(app_metrics.ListRequestBuilder)
	return ret0
}

// NewListRequestsBuilder indicates an expected call of NewListRequestsBuilder.
func (mr *MockLogRetrieverMockRecorder) NewListRequestsBuilder() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewListRequestsBuilder", reflect.TypeOf((*MockLogRetriever)(nil).NewListRequestsBuilder))
}

// QueryRequestEventMetrics mocks base method.
func (m *MockLogRetriever) QueryRequestEventMetrics(ctx context.Context, queries []app_metrics.RequestEventMetricsQuery) ([]app_metrics.RequestEventMetricSeries, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "QueryRequestEventMetrics", ctx, queries)
	ret0, _ := ret[0].([]app_metrics.RequestEventMetricSeries)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// QueryRequestEventMetrics indicates an expected call of QueryRequestEventMetrics.
func (mr *MockLogRetrieverMockRecorder) QueryRequestEventMetrics(ctx, queries interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryRequestEventMetrics", reflect.TypeOf((*MockLogRetriever)(nil).QueryRequestEventMetrics), ctx, queries)
}
