apiVersion: apps/v1
kind: Deployment
metadata:
  name: authproxy
spec:
  template:
    spec:
      containers:
        - name: authproxy
          envFrom:
            - secretRef:
                name: demo-db
                optional: true
            - secretRef:
                name: demo-redis-creds
                optional: true
            - secretRef:
                name: demo-minio-creds
                optional: true
      volumes:
        - name: jwt-keys
          secret:
            secretName: demo-jwt
        - name: encryption-keys
          secret:
            secretName: demo-encryption
        - name: actors-keys
          secret:
            secretName: demo-actors
