apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: demo
namePrefix: demo-

resources:
  - ../../base
  - grafana.yaml
  - ingress.yaml
  - minio.yaml
  - otel-lgtm.yaml
  - postgres.yaml
  - redis.yaml

configMapGenerator:
  - name: authproxy-config
    files:
      - config.yaml=authproxy-config.yaml
  - name: grafana-dashboards
    files:
      - authproxy-app-metrics.json=dashboards/authproxy-app-metrics.json

generatorOptions:
  disableNameSuffixHash: true

images:
  - name: ghcr.io/rmorlok/authproxy
    newTag: main
  - name: ghcr.io/rmorlok/authproxy-demo-shell
    newTag: main
  - name: ghcr.io/rmorlok/authproxy-demo-grafana
    newTag: main

patches:
  - path: authproxy-secrets.yaml
  - path: demo-shell-env.yaml
