apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
  labels:
    app.kubernetes.io/name: minio
    app.kubernetes.io/component: object-storage
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: minio
      app.kubernetes.io/component: object-storage
  template:
    metadata:
      labels:
        app.kubernetes.io/name: minio
        app.kubernetes.io/component: object-storage
    spec:
      containers:
        - name: minio
          image: docker.io/bitnamilegacy/minio:2024.11.7-debian-12-r0
          imagePullPolicy: IfNotPresent
          ports:
            - name: api
              containerPort: 9000
          env:
            - name: MINIO_ROOT_USER
              value: authproxy
            - name: MINIO_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: demo-minio-creds
                  key: root-password
---
apiVersion: v1
kind: Service
metadata:
  name: minio
  labels:
    app.kubernetes.io/name: minio
    app.kubernetes.io/component: object-storage
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: minio
    app.kubernetes.io/component: object-storage
  ports:
    - name: api
      port: 9000
      targetPort: api
