public:
  port: 8080
  baseUrl: https://marketplace.branch.dev.authproxy.net
  enableProxy: true
  static: {}
api:
  port: 8081
adminApi:
  port: 8082
  ui:
    enabled: true
    baseUrl: https://admin.branch.dev.authproxy.net
    initiateSessionUrl: https://branch.dev.authproxy.net/
  static: {}
worker:
  healthCheckPort: 8083
database:
  provider: sqlite
  path: /tmp/authproxy-dev.db
redis:
  provider: miniredis
hostApplication:
  initiateSessionUrl: https://branch.dev.authproxy.net/
connectors:
  loadFromList: []
appMetrics:
  database:
    provider: sqlite
    path: /tmp/authproxy-dev.db.app-metrics
  requestEvents:
    fullRequestRecording: never
  blobStorage:
    provider: filesystem
    path: /tmp/authproxy-blobs
systemAuth:
  jwtSigningKey:
    publicKey:
      path: /etc/authproxy/keys/jwt/system.pub
    privateKey:
      path: /etc/authproxy/keys/jwt/system
  globalAesKey:
    path: /etc/authproxy/keys/encryption/global_aes.key
  actors:
    root:
      keysPath: /etc/authproxy/keys/actors/root
      permissions:
        - namespace: root.**
          resources:
            - "*"
          verbs:
            - "*"
    root.smoke:
      keysPath: /etc/authproxy/keys/actors/smoke
      permissions:
        - namespace: root.smoke
          resources:
            - connectors
          verbs:
            - list
        - namespace: root.smoke.{{external_id}}
          resources:
            - connections
          verbs:
            - create
            - get
            - proxy
    syncCronSchedule: "* * * * *"
