apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-shell
spec:
  template:
    spec:
      containers:
        - name: demo-shell
          env:
            - name: PORT
              value: "8888"
            - name: ADMIN_USERNAME
              value: demo-shell
            - name: ADMIN_PRIVATE_KEY_PATH
              value: /etc/authproxy/demo-shell/private
            - name: AUTHPROXY_AUTH_URL
              value: https://marketplace.branch.dev.authproxy.net
            - name: AUTHPROXY_MARKETPLACE_URL
              value: https://marketplace.branch.dev.authproxy.net
            - name: AUTHPROXY_ADMIN_UI_URL
              value: https://admin.branch.dev.authproxy.net
      volumes:
        - name: admin-key
          secret:
            secretName: dev-demo-shell-key
            items:
              - key: private
                path: private
