apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: authproxy-dev-placeholder
namePrefix: dev-

resources:
  - ../../base
  - ingress.yaml

configMapGenerator:
  - name: authproxy-config
    files:
      - config.yaml=authproxy-config.yaml

generatorOptions:
  disableNameSuffixHash: true

patches:
  - path: authproxy-secrets.yaml
  - path: demo-shell-env.yaml
