adminUsername: bobdole
adminPrivateKeyPath: /home/bob/.authproxy/admin.key
adminSharedKeyPath: /home/bob/.authproxy/shared.key
server:
  api: http://localhost:8081
  adminApi: http://localhost:8082
  auth: http://localhost:8080
  marketplace: http://localhost:5173
  adminUi: http://localhost:5174
signingProxy:
  port:
    envVar: AUTHPROXY_SIGNING_PROXY_PORT
    default: "8888"
