apiVersion: authproxy.net/v1alpha1
kind: Connector
metadata:
  labels:
    env: prod
    type: google-drive
  name: google-drive
  namespace: root
spec:
  definition:
    auth:
      authorization:
        endpoint: https://accounts.google.com/o/oauth2/v2/auth
        queryOverrides:
          prompt: consent
      clientId:
        envVar: GOOGLE_CLIENT_ID
      clientSecret:
        envVar: GOOGLE_CLIENT_SECRET
      revocation:
        endpoint: https://oauth2.googleapis.com/revoke
        supportedTokens: refresh_token
      scopes:
        - id: https://www.googleapis.com/auth/drive.readonly
          reason: |
            We need to be able to view the files
      token:
        endpoint: https://oauth2.googleapis.com/token
      type: OAuth2
    description: |
      This integration connects Google Drive to Acme app.
    displayName: Google Drive
    highlight: |
      Have the agent track your work in Google Drive.
    logo:
      publicUrl: https://upload.wikimedia.org/wikipedia/commons/thumb/1/12/Google_Drive_icon_%282020%29.svg/1024px-Google_Drive_icon_%282020%29.svg.png?20221103153031
