// Code generated by MockGen. DO NOT EDIT.
// Source: ./interface.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"
	time "time"

	gomock "github.com/golang/mock/gomock"
	apid "github.com/rmorlok/authproxy/internal/apid"
	database "github.com/rmorlok/authproxy/internal/database"
	encfield "github.com/rmorlok/authproxy/internal/encfield"
	auth "github.com/rmorlok/authproxy/internal/schema/auth"
	connectors "github.com/rmorlok/authproxy/internal/schema/resources/connectors"
	rate_limit "github.com/rmorlok/authproxy/internal/schema/resources/rate_limit"
	pagination "github.com/rmorlok/authproxy/internal/util/pagination"
	rate "golang.org/x/time/rate"
)

// MockIActorData is a mock of IActorData interface.
type MockIActorData struct {
	ctrl     *gomock.Controller
	recorder *MockIActorDataMockRecorder
}

// MockIActorDataMockRecorder is the mock recorder for MockIActorData.
type MockIActorDataMockRecorder struct {
	mock *MockIActorData
}

// NewMockIActorData creates a new mock instance.
func NewMockIActorData(ctrl *gomock.Controller) *MockIActorData {
	mock := &MockIActorData{ctrl: ctrl}
	mock.recorder = &MockIActorDataMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIActorData) EXPECT() *MockIActorDataMockRecorder {
	return m.recorder
}

// GetAnnotations mocks base method.
func (m *MockIActorData) GetAnnotations() map[string]string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAnnotations")
	ret0, _ := ret[0].(map[string]string)
	return ret0
}

// GetAnnotations indicates an expected call of GetAnnotations.
func (mr *MockIActorDataMockRecorder) GetAnnotations() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAnnotations", reflect.TypeOf((*MockIActorData)(nil).GetAnnotations))
}

// GetExternalId mocks base method.
func (m *MockIActorData) GetExternalId() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetExternalId")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetExternalId indicates an expected call of GetExternalId.
func (mr *MockIActorDataMockRecorder) GetExternalId() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetExternalId", reflect.TypeOf((*MockIActorData)(nil).GetExternalId))
}

// GetId mocks base method.
func (m *MockIActorData) GetId() apid.ID {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetId")
	ret0, _ := ret[0].(apid.ID)
	return ret0
}

// GetId indicates an expected call of GetId.
func (mr *MockIActorDataMockRecorder) GetId() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetId", reflect.TypeOf((*MockIActorData)(nil).GetId))
}

// GetLabels mocks base method.
func (m *MockIActorData) GetLabels() map[string]string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLabels")
	ret0, _ := ret[0].(map[string]string)
	return ret0
}

// GetLabels indicates an expected call of GetLabels.
func (mr *MockIActorDataMockRecorder) GetLabels() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLabels", reflect.TypeOf((*MockIActorData)(nil).GetLabels))
}

// GetNamespace mocks base method.
func (m *MockIActorData) GetNamespace() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNamespace")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetNamespace indicates an expected call of GetNamespace.
func (mr *MockIActorDataMockRecorder) GetNamespace() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNamespace", reflect.TypeOf((*MockIActorData)(nil).GetNamespace))
}

// GetPermissions mocks base method.
func (m *MockIActorData) GetPermissions() []auth.Permission {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPermissions")
	ret0, _ := ret[0].([]auth.Permission)
	return ret0
}

// GetPermissions indicates an expected call of GetPermissions.
func (mr *MockIActorDataMockRecorder) GetPermissions() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPermissions", reflect.TypeOf((*MockIActorData)(nil).GetPermissions))
}

// MockIActorDataExtended is a mock of IActorDataExtended interface.
type MockIActorDataExtended struct {
	ctrl     *gomock.Controller
	recorder *MockIActorDataExtendedMockRecorder
}

// MockIActorDataExtendedMockRecorder is the mock recorder for MockIActorDataExtended.
type MockIActorDataExtendedMockRecorder struct {
	mock *MockIActorDataExtended
}

// NewMockIActorDataExtended creates a new mock instance.
func NewMockIActorDataExtended(ctrl *gomock.Controller) *MockIActorDataExtended {
	mock := &MockIActorDataExtended{ctrl: ctrl}
	mock.recorder = &MockIActorDataExtendedMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIActorDataExtended) EXPECT() *MockIActorDataExtendedMockRecorder {
	return m.recorder
}

// GetAnnotations mocks base method.
func (m *MockIActorDataExtended) GetAnnotations() map[string]string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAnnotations")
	ret0, _ := ret[0].(map[string]string)
	return ret0
}

// GetAnnotations indicates an expected call of GetAnnotations.
func (mr *MockIActorDataExtendedMockRecorder) GetAnnotations() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAnnotations", reflect.TypeOf((*MockIActorDataExtended)(nil).GetAnnotations))
}

// GetEncryptedKey mocks base method.
func (m *MockIActorDataExtended) GetEncryptedKey() *encfield.EncryptedField {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEncryptedKey")
	ret0, _ := ret[0].(*encfield.EncryptedField)
	return ret0
}

// GetEncryptedKey indicates an expected call of GetEncryptedKey.
func (mr *MockIActorDataExtendedMockRecorder) GetEncryptedKey() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEncryptedKey", reflect.TypeOf((*MockIActorDataExtended)(nil).GetEncryptedKey))
}

// GetExternalId mocks base method.
func (m *MockIActorDataExtended) GetExternalId() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetExternalId")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetExternalId indicates an expected call of GetExternalId.
func (mr *MockIActorDataExtendedMockRecorder) GetExternalId() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetExternalId", reflect.TypeOf((*MockIActorDataExtended)(nil).GetExternalId))
}

// GetId mocks base method.
func (m *MockIActorDataExtended) GetId() apid.ID {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetId")
	ret0, _ := ret[0].(apid.ID)
	return ret0
}

// GetId indicates an expected call of GetId.
func (mr *MockIActorDataExtendedMockRecorder) GetId() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetId", reflect.TypeOf((*MockIActorDataExtended)(nil).GetId))
}

// GetLabels mocks base method.
func (m *MockIActorDataExtended) GetLabels() map[string]string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLabels")
	ret0, _ := ret[0].(map[string]string)
	return ret0
}

// GetLabels indicates an expected call of GetLabels.
func (mr *MockIActorDataExtendedMockRecorder) GetLabels() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLabels", reflect.TypeOf((*MockIActorDataExtended)(nil).GetLabels))
}

// GetNamespace mocks base method.
func (m *MockIActorDataExtended) GetNamespace() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNamespace")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetNamespace indicates an expected call of GetNamespace.
func (mr *MockIActorDataExtendedMockRecorder) GetNamespace() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNamespace", reflect.TypeOf((*MockIActorDataExtended)(nil).GetNamespace))
}

// GetPermissions mocks base method.
func (m *MockIActorDataExtended) GetPermissions() []auth.Permission {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPermissions")
	ret0, _ := ret[0].([]auth.Permission)
	return ret0
}

// GetPermissions indicates an expected call of GetPermissions.
func (mr *MockIActorDataExtendedMockRecorder) GetPermissions() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPermissions", reflect.TypeOf((*MockIActorDataExtended)(nil).GetPermissions))
}

// MockDB is a mock of DB interface.
type MockDB struct {
	ctrl     *gomock.Controller
	recorder *MockDBMockRecorder
}

// MockDBMockRecorder is the mock recorder for MockDB.
type MockDBMockRecorder struct {
	mock *MockDB
}

// NewMockDB creates a new mock instance.
func NewMockDB(ctrl *gomock.Controller) *MockDB {
	mock := &MockDB{ctrl: ctrl}
	mock.recorder = &MockDBMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDB) EXPECT() *MockDBMockRecorder {
	return m.recorder
}

// BatchUpdateReEncryptedFields mocks base method.
func (m *MockDB) BatchUpdateReEncryptedFields(ctx context.Context, updates []database.ReEncryptedFieldUpdate) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchUpdateReEncryptedFields", ctx, updates)
	ret0, _ := ret[0].(error)
	return ret0
}

// BatchUpdateReEncryptedFields indicates an expected call of BatchUpdateReEncryptedFields.
func (mr *MockDBMockRecorder) BatchUpdateReEncryptedFields(ctx, updates interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchUpdateReEncryptedFields", reflect.TypeOf((*MockDB)(nil).BatchUpdateReEncryptedFields), ctx, updates)
}

// CheckNonceValidAndMarkUsed mocks base method.
func (m *MockDB) CheckNonceValidAndMarkUsed(ctx context.Context, nonce apid.ID, retainRecordUntil time.Time) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckNonceValidAndMarkUsed", ctx, nonce, retainRecordUntil)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckNonceValidAndMarkUsed indicates an expected call of CheckNonceValidAndMarkUsed.
func (mr *MockDBMockRecorder) CheckNonceValidAndMarkUsed(ctx, nonce, retainRecordUntil interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckNonceValidAndMarkUsed", reflect.TypeOf((*MockDB)(nil).CheckNonceValidAndMarkUsed), ctx, nonce, retainRecordUntil)
}

// ClearCurrentDataEncryptionKeyFlagForKey mocks base method.
func (m *MockDB) ClearCurrentDataEncryptionKeyFlagForKey(ctx context.Context, keyId apid.ID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClearCurrentDataEncryptionKeyFlagForKey", ctx, keyId)
	ret0, _ := ret[0].(error)
	return ret0
}

// ClearCurrentDataEncryptionKeyFlagForKey indicates an expected call of ClearCurrentDataEncryptionKeyFlagForKey.
func (mr *MockDBMockRecorder) ClearCurrentDataEncryptionKeyFlagForKey(ctx, keyId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClearCurrentDataEncryptionKeyFlagForKey", reflect.TypeOf((*MockDB)(nil).ClearCurrentDataEncryptionKeyFlagForKey), ctx, keyId)
}

// CountProbeOutcomes mocks base method.
func (m *MockDB) CountProbeOutcomes(ctx context.Context, connectionId apid.ID, probeId string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountProbeOutcomes", ctx, connectionId, probeId)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountProbeOutcomes indicates an expected call of CountProbeOutcomes.
func (mr *MockDBMockRecorder) CountProbeOutcomes(ctx, connectionId, probeId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountProbeOutcomes", reflect.TypeOf((*MockDB)(nil).CountProbeOutcomes), ctx, connectionId, probeId)
}

// CreateActor mocks base method.
func (m *MockDB) CreateActor(ctx context.Context, actor *database.Actor) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateActor", ctx, actor)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateActor indicates an expected call of CreateActor.
func (mr *MockDBMockRecorder) CreateActor(ctx, actor interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateActor", reflect.TypeOf((*MockDB)(nil).CreateActor), ctx, actor)
}

// CreateConnection mocks base method.
func (m *MockDB) CreateConnection(ctx context.Context, c *database.Connection) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateConnection", ctx, c)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateConnection indicates an expected call of CreateConnection.
func (mr *MockDBMockRecorder) CreateConnection(ctx, c interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateConnection", reflect.TypeOf((*MockDB)(nil).CreateConnection), ctx, c)
}

// CreateDataEncryptionKey mocks base method.
func (m *MockDB) CreateDataEncryptionKey(ctx context.Context, dek *database.DataEncryptionKey) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateDataEncryptionKey", ctx, dek)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateDataEncryptionKey indicates an expected call of CreateDataEncryptionKey.
func (mr *MockDBMockRecorder) CreateDataEncryptionKey(ctx, dek interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateDataEncryptionKey", reflect.TypeOf((*MockDB)(nil).CreateDataEncryptionKey), ctx, dek)
}

// CreateKey mocks base method.
func (m *MockDB) CreateKey(ctx context.Context, ek *database.Key) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateKey", ctx, ek)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateKey indicates an expected call of CreateKey.
func (mr *MockDBMockRecorder) CreateKey(ctx, ek interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateKey", reflect.TypeOf((*MockDB)(nil).CreateKey), ctx, ek)
}

// CreateNamespace mocks base method.
func (m *MockDB) CreateNamespace(ctx context.Context, ns *database.Namespace) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateNamespace", ctx, ns)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateNamespace indicates an expected call of CreateNamespace.
func (mr *MockDBMockRecorder) CreateNamespace(ctx, ns interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateNamespace", reflect.TypeOf((*MockDB)(nil).CreateNamespace), ctx, ns)
}

// CreateRateLimit mocks base method.
func (m *MockDB) CreateRateLimit(ctx context.Context, rl *database.RateLimit) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateRateLimit", ctx, rl)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateRateLimit indicates an expected call of CreateRateLimit.
func (mr *MockDBMockRecorder) CreateRateLimit(ctx, rl interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateRateLimit", reflect.TypeOf((*MockDB)(nil).CreateRateLimit), ctx, rl)
}

// DeleteActor mocks base method.
func (m *MockDB) DeleteActor(ctx context.Context, id apid.ID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteActor", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteActor indicates an expected call of DeleteActor.
func (mr *MockDBMockRecorder) DeleteActor(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteActor", reflect.TypeOf((*MockDB)(nil).DeleteActor), ctx, id)
}

// DeleteActorAnnotations mocks base method.
func (m *MockDB) DeleteActorAnnotations(ctx context.Context, id apid.ID, keys []string) (*database.Actor, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteActorAnnotations", ctx, id, keys)
	ret0, _ := ret[0].(*database.Actor)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteActorAnnotations indicates an expected call of DeleteActorAnnotations.
func (mr *MockDBMockRecorder) DeleteActorAnnotations(ctx, id, keys interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteActorAnnotations", reflect.TypeOf((*MockDB)(nil).DeleteActorAnnotations), ctx, id, keys)
}

// DeleteActorLabels mocks base method.
func (m *MockDB) DeleteActorLabels(ctx context.Context, id apid.ID, keys []string) (*database.Actor, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteActorLabels", ctx, id, keys)
	ret0, _ := ret[0].(*database.Actor)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteActorLabels indicates an expected call of DeleteActorLabels.
func (mr *MockDBMockRecorder) DeleteActorLabels(ctx, id, keys interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteActorLabels", reflect.TypeOf((*MockDB)(nil).DeleteActorLabels), ctx, id, keys)
}

// DeleteAllApiKeyCredentialsForConnection mocks base method.
func (m *MockDB) DeleteAllApiKeyCredentialsForConnection(ctx context.Context, connectionId apid.ID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAllApiKeyCredentialsForConnection", ctx, connectionId)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAllApiKeyCredentialsForConnection indicates an expected call of DeleteAllApiKeyCredentialsForConnection.
func (mr *MockDBMockRecorder) DeleteAllApiKeyCredentialsForConnection(ctx, connectionId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAllApiKeyCredentialsForConnection", reflect.TypeOf((*MockDB)(nil).DeleteAllApiKeyCredentialsForConnection), ctx, connectionId)
}

// DeleteAllOAuth2TokensForConnection mocks base method.
func (m *MockDB) DeleteAllOAuth2TokensForConnection(ctx context.Context, connectionId apid.ID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAllOAuth2TokensForConnection", ctx, connectionId)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAllOAuth2TokensForConnection indicates an expected call of DeleteAllOAuth2TokensForConnection.
func (mr *MockDBMockRecorder) DeleteAllOAuth2TokensForConnection(ctx, connectionId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAllOAuth2TokensForConnection", reflect.TypeOf((*MockDB)(nil).DeleteAllOAuth2TokensForConnection), ctx, connectionId)
}

// DeleteConnection mocks base method.
func (m *MockDB) DeleteConnection(ctx context.Context, id apid.ID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteConnection", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteConnection indicates an expected call of DeleteConnection.
func (mr *MockDBMockRecorder) DeleteConnection(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteConnection", reflect.TypeOf((*MockDB)(nil).DeleteConnection), ctx, id)
}

// DeleteConnectionAnnotations mocks base method.
func (m *MockDB) DeleteConnectionAnnotations(ctx context.Context, id apid.ID, keys []string) (*database.Connection, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteConnectionAnnotations", ctx, id, keys)
	ret0, _ := ret[0].(*database.Connection)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteConnectionAnnotations indicates an expected call of DeleteConnectionAnnotations.
func (mr *MockDBMockRecorder) DeleteConnectionAnnotations(ctx, id, keys interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteConnectionAnnotations", reflect.TypeOf((*MockDB)(nil).DeleteConnectionAnnotations), ctx, id, keys)
}

// DeleteConnectionLabels mocks base method.
func (m *MockDB) DeleteConnectionLabels(ctx context.Context, id apid.ID, keys []string) (*database.Connection, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteConnectionLabels", ctx, id, keys)
	ret0, _ := ret[0].(*database.Connection)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteConnectionLabels indicates an expected call of DeleteConnectionLabels.
func (mr *MockDBMockRecorder) DeleteConnectionLabels(ctx, id, keys interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteConnectionLabels", reflect.TypeOf((*MockDB)(nil).DeleteConnectionLabels), ctx, id, keys)
}

// DeleteConnector mocks base method.
func (m *MockDB) DeleteConnector(ctx context.Context, id apid.ID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteConnector", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteConnector indicates an expected call of DeleteConnector.
func (mr *MockDBMockRecorder) DeleteConnector(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteConnector", reflect.TypeOf((*MockDB)(nil).DeleteConnector), ctx, id)
}

// DeleteExpiredNonces mocks base method.
func (m *MockDB) DeleteExpiredNonces(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteExpiredNonces", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteExpiredNonces indicates an expected call of DeleteExpiredNonces.
func (mr *MockDBMockRecorder) DeleteExpiredNonces(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteExpiredNonces", reflect.TypeOf((*MockDB)(nil).DeleteExpiredNonces), ctx)
}

// DeleteKey mocks base method.
func (m *MockDB) DeleteKey(ctx context.Context, id apid.ID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteKey", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteKey indicates an expected call of DeleteKey.
func (mr *MockDBMockRecorder) DeleteKey(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteKey", reflect.TypeOf((*MockDB)(nil).DeleteKey), ctx, id)
}

// DeleteKeyAnnotations mocks base method.
func (m *MockDB) DeleteKeyAnnotations(ctx context.Context, id apid.ID, keys []string) (*database.Key, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteKeyAnnotations", ctx, id, keys)
	ret0, _ := ret[0].(*database.Key)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteKeyAnnotations indicates an expected call of DeleteKeyAnnotations.
func (mr *MockDBMockRecorder) DeleteKeyAnnotations(ctx, id, keys interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteKeyAnnotations", reflect.TypeOf((*MockDB)(nil).DeleteKeyAnnotations), ctx, id, keys)
}

// DeleteKeyLabels mocks base method.
func (m *MockDB) DeleteKeyLabels(ctx context.Context, id apid.ID, keys []string) (*database.Key, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteKeyLabels", ctx, id, keys)
	ret0, _ := ret[0].(*database.Key)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteKeyLabels indicates an expected call of DeleteKeyLabels.
func (mr *MockDBMockRecorder) DeleteKeyLabels(ctx, id, keys interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteKeyLabels", reflect.TypeOf((*MockDB)(nil).DeleteKeyLabels), ctx, id, keys)
}

// DeleteNamespace mocks base method.
func (m *MockDB) DeleteNamespace(ctx context.Context, path string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteNamespace", ctx, path)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteNamespace indicates an expected call of DeleteNamespace.
func (mr *MockDBMockRecorder) DeleteNamespace(ctx, path interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteNamespace", reflect.TypeOf((*MockDB)(nil).DeleteNamespace), ctx, path)
}

// DeleteNamespaceAnnotations mocks base method.
func (m *MockDB) DeleteNamespaceAnnotations(ctx context.Context, path string, keys []string) (*database.Namespace, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteNamespaceAnnotations", ctx, path, keys)
	ret0, _ := ret[0].(*database.Namespace)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteNamespaceAnnotations indicates an expected call of DeleteNamespaceAnnotations.
func (mr *MockDBMockRecorder) DeleteNamespaceAnnotations(ctx, path, keys interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteNamespaceAnnotations", reflect.TypeOf((*MockDB)(nil).DeleteNamespaceAnnotations), ctx, path, keys)
}

// DeleteNamespaceLabels mocks base method.
func (m *MockDB) DeleteNamespaceLabels(ctx context.Context, path string, keys []string) (*database.Namespace, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteNamespaceLabels", ctx, path, keys)
	ret0, _ := ret[0].(*database.Namespace)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteNamespaceLabels indicates an expected call of DeleteNamespaceLabels.
func (mr *MockDBMockRecorder) DeleteNamespaceLabels(ctx, path, keys interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteNamespaceLabels", reflect.TypeOf((*MockDB)(nil).DeleteNamespaceLabels), ctx, path, keys)
}

// DeleteOAuth2Token mocks base method.
func (m *MockDB) DeleteOAuth2Token(ctx context.Context, tokenId apid.ID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteOAuth2Token", ctx, tokenId)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteOAuth2Token indicates an expected call of DeleteOAuth2Token.
func (mr *MockDBMockRecorder) DeleteOAuth2Token(ctx, tokenId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteOAuth2Token", reflect.TypeOf((*MockDB)(nil).DeleteOAuth2Token), ctx, tokenId)
}

// DeleteOldProbeOutcomes mocks base method.
func (m *MockDB) DeleteOldProbeOutcomes(ctx context.Context, connectionId apid.ID, probeId string, keepMinimum int, olderThan time.Time) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteOldProbeOutcomes", ctx, connectionId, probeId, keepMinimum, olderThan)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteOldProbeOutcomes indicates an expected call of DeleteOldProbeOutcomes.
func (mr *MockDBMockRecorder) DeleteOldProbeOutcomes(ctx, connectionId, probeId, keepMinimum, olderThan interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteOldProbeOutcomes", reflect.TypeOf((*MockDB)(nil).DeleteOldProbeOutcomes), ctx, connectionId, probeId, keepMinimum, olderThan)
}

// DeleteRateLimit mocks base method.
func (m *MockDB) DeleteRateLimit(ctx context.Context, id apid.ID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteRateLimit", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteRateLimit indicates an expected call of DeleteRateLimit.
func (mr *MockDBMockRecorder) DeleteRateLimit(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteRateLimit", reflect.TypeOf((*MockDB)(nil).DeleteRateLimit), ctx, id)
}

// DeleteRateLimitAnnotations mocks base method.
func (m *MockDB) DeleteRateLimitAnnotations(ctx context.Context, id apid.ID, keys []string) (*database.RateLimit, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteRateLimitAnnotations", ctx, id, keys)
	ret0, _ := ret[0].(*database.RateLimit)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteRateLimitAnnotations indicates an expected call of DeleteRateLimitAnnotations.
func (mr *MockDBMockRecorder) DeleteRateLimitAnnotations(ctx, id, keys interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteRateLimitAnnotations", reflect.TypeOf((*MockDB)(nil).DeleteRateLimitAnnotations), ctx, id, keys)
}

// DeleteRateLimitLabels mocks base method.
func (m *MockDB) DeleteRateLimitLabels(ctx context.Context, id apid.ID, keys []string) (*database.RateLimit, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteRateLimitLabels", ctx, id, keys)
	ret0, _ := ret[0].(*database.RateLimit)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteRateLimitLabels indicates an expected call of DeleteRateLimitLabels.
func (mr *MockDBMockRecorder) DeleteRateLimitLabels(ctx, id, keys interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteRateLimitLabels", reflect.TypeOf((*MockDB)(nil).DeleteRateLimitLabels), ctx, id, keys)
}

// DistinctProbeIdsForConnection mocks base method.
func (m *MockDB) DistinctProbeIdsForConnection(ctx context.Context, connectionId apid.ID) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DistinctProbeIdsForConnection", ctx, connectionId)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DistinctProbeIdsForConnection indicates an expected call of DistinctProbeIdsForConnection.
func (mr *MockDBMockRecorder) DistinctProbeIdsForConnection(ctx, connectionId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DistinctProbeIdsForConnection", reflect.TypeOf((*MockDB)(nil).DistinctProbeIdsForConnection), ctx, connectionId)
}

// EnsureNamespaceByPath mocks base method.
func (m *MockDB) EnsureNamespaceByPath(ctx context.Context, path string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnsureNamespaceByPath", ctx, path)
	ret0, _ := ret[0].(error)
	return ret0
}

// EnsureNamespaceByPath indicates an expected call of EnsureNamespaceByPath.
func (mr *MockDBMockRecorder) EnsureNamespaceByPath(ctx, path interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnsureNamespaceByPath", reflect.TypeOf((*MockDB)(nil).EnsureNamespaceByPath), ctx, path)
}

// EnumerateDataEncryptionKeysForKey mocks base method.
func (m *MockDB) EnumerateDataEncryptionKeysForKey(ctx context.Context, keyId apid.ID, callback func([]*database.DataEncryptionKey, bool) (pagination.KeepGoing, error)) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnumerateDataEncryptionKeysForKey", ctx, keyId, callback)
	ret0, _ := ret[0].(error)
	return ret0
}

// EnumerateDataEncryptionKeysForKey indicates an expected call of EnumerateDataEncryptionKeysForKey.
func (mr *MockDBMockRecorder) EnumerateDataEncryptionKeysForKey(ctx, keyId, callback interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnumerateDataEncryptionKeysForKey", reflect.TypeOf((*MockDB)(nil).EnumerateDataEncryptionKeysForKey), ctx, keyId, callback)
}

// EnumerateFieldsRequiringReEncryption mocks base method.
func (m *MockDB) EnumerateFieldsRequiringReEncryption(ctx context.Context, callback func([]database.ReEncryptionTarget, bool) (pagination.KeepGoing, error)) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnumerateFieldsRequiringReEncryption", ctx, callback)
	ret0, _ := ret[0].(error)
	return ret0
}

// EnumerateFieldsRequiringReEncryption indicates an expected call of EnumerateFieldsRequiringReEncryption.
func (mr *MockDBMockRecorder) EnumerateFieldsRequiringReEncryption(ctx, callback interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnumerateFieldsRequiringReEncryption", reflect.TypeOf((*MockDB)(nil).EnumerateFieldsRequiringReEncryption), ctx, callback)
}

// EnumerateKeysInDependencyOrder mocks base method.
func (m *MockDB) EnumerateKeysInDependencyOrder(ctx context.Context, callback func([]*database.Key, int) (pagination.KeepGoing, error)) ([]*database.Key, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnumerateKeysInDependencyOrder", ctx, callback)
	ret0, _ := ret[0].([]*database.Key)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EnumerateKeysInDependencyOrder indicates an expected call of EnumerateKeysInDependencyOrder.
func (mr *MockDBMockRecorder) EnumerateKeysInDependencyOrder(ctx, callback interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnumerateKeysInDependencyOrder", reflect.TypeOf((*MockDB)(nil).EnumerateKeysInDependencyOrder), ctx, callback)
}

// EnumerateNamespaceEncryptionTargets mocks base method.
func (m *MockDB) EnumerateNamespaceEncryptionTargets(ctx context.Context, callback func([]database.NamespaceEncryptionTarget, bool) ([]database.NamespaceTargetDataEncryptionKeyUpdate, pagination.KeepGoing, error)) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnumerateNamespaceEncryptionTargets", ctx, callback)
	ret0, _ := ret[0].(error)
	return ret0
}

// EnumerateNamespaceEncryptionTargets indicates an expected call of EnumerateNamespaceEncryptionTargets.
func (mr *MockDBMockRecorder) EnumerateNamespaceEncryptionTargets(ctx, callback interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnumerateNamespaceEncryptionTargets", reflect.TypeOf((*MockDB)(nil).EnumerateNamespaceEncryptionTargets), ctx, callback)
}

// EnumerateOAuth2TokensExpiringWithin mocks base method.
func (m *MockDB) EnumerateOAuth2TokensExpiringWithin(ctx context.Context, duration time.Duration, callback func([]*database.OAuth2TokenWithConnection, bool) (pagination.KeepGoing, error)) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnumerateOAuth2TokensExpiringWithin", ctx, duration, callback)
	ret0, _ := ret[0].(error)
	return ret0
}

// EnumerateOAuth2TokensExpiringWithin indicates an expected call of EnumerateOAuth2TokensExpiringWithin.
func (mr *MockDBMockRecorder) EnumerateOAuth2TokensExpiringWithin(ctx, duration, callback interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnumerateOAuth2TokensExpiringWithin", reflect.TypeOf((*MockDB)(nil).EnumerateOAuth2TokensExpiringWithin), ctx, duration, callback)
}

// GetActiveApiKeyCredential mocks base method.
func (m *MockDB) GetActiveApiKeyCredential(ctx context.Context, connectionId apid.ID) (*database.ApiKeyCredential, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActiveApiKeyCredential", ctx, connectionId)
	ret0, _ := ret[0].(*database.ApiKeyCredential)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetActiveApiKeyCredential indicates an expected call of GetActiveApiKeyCredential.
func (mr *MockDBMockRecorder) GetActiveApiKeyCredential(ctx, connectionId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActiveApiKeyCredential", reflect.TypeOf((*MockDB)(nil).GetActiveApiKeyCredential), ctx, connectionId)
}

// GetActor mocks base method.
func (m *MockDB) GetActor(ctx context.Context, id apid.ID) (*database.Actor, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActor", ctx, id)
	ret0, _ := ret[0].(*database.Actor)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetActor indicates an expected call of GetActor.
func (mr *MockDBMockRecorder) GetActor(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActor", reflect.TypeOf((*MockDB)(nil).GetActor), ctx, id)
}

// GetActorByExternalId mocks base method.
func (m *MockDB) GetActorByExternalId(ctx context.Context, namespace, externalId string) (*database.Actor, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActorByExternalId", ctx, namespace, externalId)
	ret0, _ := ret[0].(*database.Actor)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetActorByExternalId indicates an expected call of GetActorByExternalId.
func (mr *MockDBMockRecorder) GetActorByExternalId(ctx, namespace, externalId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActorByExternalId", reflect.TypeOf((*MockDB)(nil).GetActorByExternalId), ctx, namespace, externalId)
}

// GetConnection mocks base method.
func (m *MockDB) GetConnection(ctx context.Context, id apid.ID) (*database.Connection, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetConnection", ctx, id)
	ret0, _ := ret[0].(*database.Connection)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetConnection indicates an expected call of GetConnection.
func (mr *MockDBMockRecorder) GetConnection(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConnection", reflect.TypeOf((*MockDB)(nil).GetConnection), ctx, id)
}

// GetConnectorVersion mocks base method.
func (m *MockDB) GetConnectorVersion(ctx context.Context, id apid.ID, version uint64) (*database.ConnectorVersion, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetConnectorVersion", ctx, id, version)
	ret0, _ := ret[0].(*database.ConnectorVersion)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetConnectorVersion indicates an expected call of GetConnectorVersion.
func (mr *MockDBMockRecorder) GetConnectorVersion(ctx, id, version interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConnectorVersion", reflect.TypeOf((*MockDB)(nil).GetConnectorVersion), ctx, id, version)
}

// GetConnectorVersionForLabels mocks base method.
func (m *MockDB) GetConnectorVersionForLabels(ctx context.Context, labelSelector string) (*database.ConnectorVersion, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetConnectorVersionForLabels", ctx, labelSelector)
	ret0, _ := ret[0].(*database.ConnectorVersion)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetConnectorVersionForLabels indicates an expected call of GetConnectorVersionForLabels.
func (mr *MockDBMockRecorder) GetConnectorVersionForLabels(ctx, labelSelector interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConnectorVersionForLabels", reflect.TypeOf((*MockDB)(nil).GetConnectorVersionForLabels), ctx, labelSelector)
}

// GetConnectorVersionForLabelsAndVersion mocks base method.
func (m *MockDB) GetConnectorVersionForLabelsAndVersion(ctx context.Context, labelSelector string, version uint64) (*database.ConnectorVersion, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetConnectorVersionForLabelsAndVersion", ctx, labelSelector, version)
	ret0, _ := ret[0].(*database.ConnectorVersion)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetConnectorVersionForLabelsAndVersion indicates an expected call of GetConnectorVersionForLabelsAndVersion.
func (mr *MockDBMockRecorder) GetConnectorVersionForLabelsAndVersion(ctx, labelSelector, version interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConnectorVersionForLabelsAndVersion", reflect.TypeOf((*MockDB)(nil).GetConnectorVersionForLabelsAndVersion), ctx, labelSelector, version)
}

// GetConnectorVersionForState mocks base method.
func (m *MockDB) GetConnectorVersionForState(ctx context.Context, id apid.ID, state database.ConnectorVersionState) (*database.ConnectorVersion, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetConnectorVersionForState", ctx, id, state)
	ret0, _ := ret[0].(*database.ConnectorVersion)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetConnectorVersionForState indicates an expected call of GetConnectorVersionForState.
func (mr *MockDBMockRecorder) GetConnectorVersionForState(ctx, id, state interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConnectorVersionForState", reflect.TypeOf((*MockDB)(nil).GetConnectorVersionForState), ctx, id, state)
}

// GetConnectorVersions mocks base method.
func (m *MockDB) GetConnectorVersions(ctx context.Context, requested []database.ConnectorVersionId) (map[database.ConnectorVersionId]*database.ConnectorVersion, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetConnectorVersions", ctx, requested)
	ret0, _ := ret[0].(map[database.ConnectorVersionId]*database.ConnectorVersion)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetConnectorVersions indicates an expected call of GetConnectorVersions.
func (mr *MockDBMockRecorder) GetConnectorVersions(ctx, requested interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConnectorVersions", reflect.TypeOf((*MockDB)(nil).GetConnectorVersions), ctx, requested)
}

// GetCurrentDataEncryptionKeyForKey mocks base method.
func (m *MockDB) GetCurrentDataEncryptionKeyForKey(ctx context.Context, keyId apid.ID) (*database.DataEncryptionKey, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCurrentDataEncryptionKeyForKey", ctx, keyId)
	ret0, _ := ret[0].(*database.DataEncryptionKey)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCurrentDataEncryptionKeyForKey indicates an expected call of GetCurrentDataEncryptionKeyForKey.
func (mr *MockDBMockRecorder) GetCurrentDataEncryptionKeyForKey(ctx, keyId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCurrentDataEncryptionKeyForKey", reflect.TypeOf((*MockDB)(nil).GetCurrentDataEncryptionKeyForKey), ctx, keyId)
}

// GetDataEncryptionKey mocks base method.
func (m *MockDB) GetDataEncryptionKey(ctx context.Context, id apid.ID) (*database.DataEncryptionKey, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDataEncryptionKey", ctx, id)
	ret0, _ := ret[0].(*database.DataEncryptionKey)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDataEncryptionKey indicates an expected call of GetDataEncryptionKey.
func (mr *MockDBMockRecorder) GetDataEncryptionKey(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDataEncryptionKey", reflect.TypeOf((*MockDB)(nil).GetDataEncryptionKey), ctx, id)
}

// GetKey mocks base method.
func (m *MockDB) GetKey(ctx context.Context, id apid.ID) (*database.Key, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetKey", ctx, id)
	ret0, _ := ret[0].(*database.Key)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetKey indicates an expected call of GetKey.
func (mr *MockDBMockRecorder) GetKey(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetKey", reflect.TypeOf((*MockDB)(nil).GetKey), ctx, id)
}

// GetNamespace mocks base method.
func (m *MockDB) GetNamespace(ctx context.Context, path string) (*database.Namespace, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNamespace", ctx, path)
	ret0, _ := ret[0].(*database.Namespace)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNamespace indicates an expected call of GetNamespace.
func (mr *MockDBMockRecorder) GetNamespace(ctx, path interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNamespace", reflect.TypeOf((*MockDB)(nil).GetNamespace), ctx, path)
}

// GetNotification mocks base method.
func (m *MockDB) GetNotification(ctx context.Context, id apid.ID) (*database.Notification, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNotification", ctx, id)
	ret0, _ := ret[0].(*database.Notification)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNotification indicates an expected call of GetNotification.
func (mr *MockDBMockRecorder) GetNotification(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNotification", reflect.TypeOf((*MockDB)(nil).GetNotification), ctx, id)
}

// GetOAuth2Token mocks base method.
func (m *MockDB) GetOAuth2Token(ctx context.Context, connectionId apid.ID) (*database.OAuth2Token, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOAuth2Token", ctx, connectionId)
	ret0, _ := ret[0].(*database.OAuth2Token)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOAuth2Token indicates an expected call of GetOAuth2Token.
func (mr *MockDBMockRecorder) GetOAuth2Token(ctx, connectionId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOAuth2Token", reflect.TypeOf((*MockDB)(nil).GetOAuth2Token), ctx, connectionId)
}

// GetRateLimit mocks base method.
func (m *MockDB) GetRateLimit(ctx context.Context, id apid.ID) (*database.RateLimit, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRateLimit", ctx, id)
	ret0, _ := ret[0].(*database.RateLimit)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRateLimit indicates an expected call of GetRateLimit.
func (mr *MockDBMockRecorder) GetRateLimit(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRateLimit", reflect.TypeOf((*MockDB)(nil).GetRateLimit), ctx, id)
}

// GetRecentProbeOutcomes mocks base method.
func (m *MockDB) GetRecentProbeOutcomes(ctx context.Context, connectionId apid.ID, probeId string, limit int) ([]*database.ConnectionProbeOutcome, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRecentProbeOutcomes", ctx, connectionId, probeId, limit)
	ret0, _ := ret[0].([]*database.ConnectionProbeOutcome)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRecentProbeOutcomes indicates an expected call of GetRecentProbeOutcomes.
func (mr *MockDBMockRecorder) GetRecentProbeOutcomes(ctx, connectionId, probeId, limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRecentProbeOutcomes", reflect.TypeOf((*MockDB)(nil).GetRecentProbeOutcomes), ctx, connectionId, probeId, limit)
}

// HasNonceBeenUsed mocks base method.
func (m *MockDB) HasNonceBeenUsed(ctx context.Context, nonce apid.ID) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasNonceBeenUsed", ctx, nonce)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HasNonceBeenUsed indicates an expected call of HasNonceBeenUsed.
func (mr *MockDBMockRecorder) HasNonceBeenUsed(ctx, nonce interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasNonceBeenUsed", reflect.TypeOf((*MockDB)(nil).HasNonceBeenUsed), ctx, nonce)
}

// InsertApiKeyCredential mocks base method.
func (m *MockDB) InsertApiKeyCredential(ctx context.Context, connectionId apid.ID, encryptedCredentials encfield.EncryptedField, placement *connectors.ApiKeyPlacement, createdByActorId *apid.ID) (*database.ApiKeyCredential, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertApiKeyCredential", ctx, connectionId, encryptedCredentials, placement, createdByActorId)
	ret0, _ := ret[0].(*database.ApiKeyCredential)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InsertApiKeyCredential indicates an expected call of InsertApiKeyCredential.
func (mr *MockDBMockRecorder) InsertApiKeyCredential(ctx, connectionId, encryptedCredentials, placement, createdByActorId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertApiKeyCredential", reflect.TypeOf((*MockDB)(nil).InsertApiKeyCredential), ctx, connectionId, encryptedCredentials, placement, createdByActorId)
}

// InsertOAuth2Token mocks base method.
func (m *MockDB) InsertOAuth2Token(ctx context.Context, connectionId apid.ID, refreshedFrom *apid.ID, encryptedRefreshToken, encryptedAccessToken encfield.EncryptedField, accessTokenExpiresAt *time.Time, scopes, requestedScopes string, createdByActorId *apid.ID) (*database.OAuth2Token, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertOAuth2Token", ctx, connectionId, refreshedFrom, encryptedRefreshToken, encryptedAccessToken, accessTokenExpiresAt, scopes, requestedScopes, createdByActorId)
	ret0, _ := ret[0].(*database.OAuth2Token)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InsertOAuth2Token indicates an expected call of InsertOAuth2Token.
func (mr *MockDBMockRecorder) InsertOAuth2Token(ctx, connectionId, refreshedFrom, encryptedRefreshToken, encryptedAccessToken, accessTokenExpiresAt, scopes, requestedScopes, createdByActorId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertOAuth2Token", reflect.TypeOf((*MockDB)(nil).InsertOAuth2Token), ctx, connectionId, refreshedFrom, encryptedRefreshToken, encryptedAccessToken, accessTokenExpiresAt, scopes, requestedScopes, createdByActorId)
}

// InsertProbeOutcome mocks base method.
func (m *MockDB) InsertProbeOutcome(ctx context.Context, connectionId apid.ID, probeId, outcome, errorMessage string) (*database.ConnectionProbeOutcome, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertProbeOutcome", ctx, connectionId, probeId, outcome, errorMessage)
	ret0, _ := ret[0].(*database.ConnectionProbeOutcome)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InsertProbeOutcome indicates an expected call of InsertProbeOutcome.
func (mr *MockDBMockRecorder) InsertProbeOutcome(ctx, connectionId, probeId, outcome, errorMessage interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertProbeOutcome", reflect.TypeOf((*MockDB)(nil).InsertProbeOutcome), ctx, connectionId, probeId, outcome, errorMessage)
}

// ListActorsBuilder mocks base method.
func (m *MockDB) ListActorsBuilder() database.ListActorsBuilder {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListActorsBuilder")
	ret0, _ := ret[0].(database.ListActorsBuilder)
	return ret0
}

// ListActorsBuilder indicates an expected call of ListActorsBuilder.
func (mr *MockDBMockRecorder) ListActorsBuilder() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListActorsBuilder", reflect.TypeOf((*MockDB)(nil).ListActorsBuilder))
}

// ListActorsFromCursor mocks base method.
func (m *MockDB) ListActorsFromCursor(ctx context.Context, cursor string) (database.ListActorsExecutor, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListActorsFromCursor", ctx, cursor)
	ret0, _ := ret[0].(database.ListActorsExecutor)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListActorsFromCursor indicates an expected call of ListActorsFromCursor.
func (mr *MockDBMockRecorder) ListActorsFromCursor(ctx, cursor interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListActorsFromCursor", reflect.TypeOf((*MockDB)(nil).ListActorsFromCursor), ctx, cursor)
}

// ListConnectionsBuilder mocks base method.
func (m *MockDB) ListConnectionsBuilder() database.ListConnectionsBuilder {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListConnectionsBuilder")
	ret0, _ := ret[0].(database.ListConnectionsBuilder)
	return ret0
}

// ListConnectionsBuilder indicates an expected call of ListConnectionsBuilder.
func (mr *MockDBMockRecorder) ListConnectionsBuilder() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListConnectionsBuilder", reflect.TypeOf((*MockDB)(nil).ListConnectionsBuilder))
}

// ListConnectionsFromCursor mocks base method.
func (m *MockDB) ListConnectionsFromCursor(ctx context.Context, cursor string) (database.ListConnectionsExecutor, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListConnectionsFromCursor", ctx, cursor)
	ret0, _ := ret[0].(database.ListConnectionsExecutor)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListConnectionsFromCursor indicates an expected call of ListConnectionsFromCursor.
func (mr *MockDBMockRecorder) ListConnectionsFromCursor(ctx, cursor interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListConnectionsFromCursor", reflect.TypeOf((*MockDB)(nil).ListConnectionsFromCursor), ctx, cursor)
}

// ListConnectorVersionsBuilder mocks base method.
func (m *MockDB) ListConnectorVersionsBuilder() database.ListConnectorVersionsBuilder {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListConnectorVersionsBuilder")
	ret0, _ := ret[0].(database.ListConnectorVersionsBuilder)
	return ret0
}

// ListConnectorVersionsBuilder indicates an expected call of ListConnectorVersionsBuilder.
func (mr *MockDBMockRecorder) ListConnectorVersionsBuilder() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListConnectorVersionsBuilder", reflect.TypeOf((*MockDB)(nil).ListConnectorVersionsBuilder))
}

// ListConnectorVersionsFromCursor mocks base method.
func (m *MockDB) ListConnectorVersionsFromCursor(ctx context.Context, cursor string) (database.ListConnectorVersionsExecutor, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListConnectorVersionsFromCursor", ctx, cursor)
	ret0, _ := ret[0].(database.ListConnectorVersionsExecutor)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListConnectorVersionsFromCursor indicates an expected call of ListConnectorVersionsFromCursor.
func (mr *MockDBMockRecorder) ListConnectorVersionsFromCursor(ctx, cursor interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListConnectorVersionsFromCursor", reflect.TypeOf((*MockDB)(nil).ListConnectorVersionsFromCursor), ctx, cursor)
}

// ListConnectorsBuilder mocks base method.
func (m *MockDB) ListConnectorsBuilder() database.ListConnectorsBuilder {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListConnectorsBuilder")
	ret0, _ := ret[0].(database.ListConnectorsBuilder)
	return ret0
}

// ListConnectorsBuilder indicates an expected call of ListConnectorsBuilder.
func (mr *MockDBMockRecorder) ListConnectorsBuilder() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListConnectorsBuilder", reflect.TypeOf((*MockDB)(nil).ListConnectorsBuilder))
}

// ListConnectorsFromCursor mocks base method.
func (m *MockDB) ListConnectorsFromCursor(ctx context.Context, cursor string) (database.ListConnectorsExecutor, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListConnectorsFromCursor", ctx, cursor)
	ret0, _ := ret[0].(database.ListConnectorsExecutor)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListConnectorsFromCursor indicates an expected call of ListConnectorsFromCursor.
func (mr *MockDBMockRecorder) ListConnectorsFromCursor(ctx, cursor interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListConnectorsFromCursor", reflect.TypeOf((*MockDB)(nil).ListConnectorsFromCursor), ctx, cursor)
}

// ListDataEncryptionKeysForKey mocks base method.
func (m *MockDB) ListDataEncryptionKeysForKey(ctx context.Context, keyId apid.ID) ([]*database.DataEncryptionKey, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListDataEncryptionKeysForKey", ctx, keyId)
	ret0, _ := ret[0].([]*database.DataEncryptionKey)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListDataEncryptionKeysForKey indicates an expected call of ListDataEncryptionKeysForKey.
func (mr *MockDBMockRecorder) ListDataEncryptionKeysForKey(ctx, keyId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListDataEncryptionKeysForKey", reflect.TypeOf((*MockDB)(nil).ListDataEncryptionKeysForKey), ctx, keyId)
}

// ListKeysBuilder mocks base method.
func (m *MockDB) ListKeysBuilder() database.ListKeysBuilder {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListKeysBuilder")
	ret0, _ := ret[0].(database.ListKeysBuilder)
	return ret0
}

// ListKeysBuilder indicates an expected call of ListKeysBuilder.
func (mr *MockDBMockRecorder) ListKeysBuilder() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListKeysBuilder", reflect.TypeOf((*MockDB)(nil).ListKeysBuilder))
}

// ListKeysFromCursor mocks base method.
func (m *MockDB) ListKeysFromCursor(ctx context.Context, cursor string) (database.ListKeysExecutor, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListKeysFromCursor", ctx, cursor)
	ret0, _ := ret[0].(database.ListKeysExecutor)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListKeysFromCursor indicates an expected call of ListKeysFromCursor.
func (mr *MockDBMockRecorder) ListKeysFromCursor(ctx, cursor interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListKeysFromCursor", reflect.TypeOf((*MockDB)(nil).ListKeysFromCursor), ctx, cursor)
}

// ListNamespacesBuilder mocks base method.
func (m *MockDB) ListNamespacesBuilder() database.ListNamespacesBuilder {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListNamespacesBuilder")
	ret0, _ := ret[0].(database.ListNamespacesBuilder)
	return ret0
}

// ListNamespacesBuilder indicates an expected call of ListNamespacesBuilder.
func (mr *MockDBMockRecorder) ListNamespacesBuilder() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListNamespacesBuilder", reflect.TypeOf((*MockDB)(nil).ListNamespacesBuilder))
}

// ListNamespacesFromCursor mocks base method.
func (m *MockDB) ListNamespacesFromCursor(ctx context.Context, cursor string) (database.ListNamespacesExecutor, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListNamespacesFromCursor", ctx, cursor)
	ret0, _ := ret[0].(database.ListNamespacesExecutor)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListNamespacesFromCursor indicates an expected call of ListNamespacesFromCursor.
func (mr *MockDBMockRecorder) ListNamespacesFromCursor(ctx, cursor interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListNamespacesFromCursor", reflect.TypeOf((*MockDB)(nil).ListNamespacesFromCursor), ctx, cursor)
}

// ListNotifications mocks base method.
func (m *MockDB) ListNotifications(ctx context.Context, opts database.ListNotificationsOptions) ([]database.Notification, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListNotifications", ctx, opts)
	ret0, _ := ret[0].([]database.Notification)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListNotifications indicates an expected call of ListNotifications.
func (mr *MockDBMockRecorder) ListNotifications(ctx, opts interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListNotifications", reflect.TypeOf((*MockDB)(nil).ListNotifications), ctx, opts)
}

// ListRateLimitsBuilder mocks base method.
func (m *MockDB) ListRateLimitsBuilder() database.ListRateLimitsBuilder {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListRateLimitsBuilder")
	ret0, _ := ret[0].(database.ListRateLimitsBuilder)
	return ret0
}

// ListRateLimitsBuilder indicates an expected call of ListRateLimitsBuilder.
func (mr *MockDBMockRecorder) ListRateLimitsBuilder() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListRateLimitsBuilder", reflect.TypeOf((*MockDB)(nil).ListRateLimitsBuilder))
}

// ListRateLimitsFromCursor mocks base method.
func (m *MockDB) ListRateLimitsFromCursor(ctx context.Context, cursor string) (database.ListRateLimitsExecutor, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListRateLimitsFromCursor", ctx, cursor)
	ret0, _ := ret[0].(database.ListRateLimitsExecutor)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListRateLimitsFromCursor indicates an expected call of ListRateLimitsFromCursor.
func (mr *MockDBMockRecorder) ListRateLimitsFromCursor(ctx, cursor interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListRateLimitsFromCursor", reflect.TypeOf((*MockDB)(nil).ListRateLimitsFromCursor), ctx, cursor)
}

// MarkNotificationViewed mocks base method.
func (m *MockDB) MarkNotificationViewed(ctx context.Context, notificationID, actorID apid.ID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkNotificationViewed", ctx, notificationID, actorID)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkNotificationViewed indicates an expected call of MarkNotificationViewed.
func (mr *MockDBMockRecorder) MarkNotificationViewed(ctx, notificationID, actorID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkNotificationViewed", reflect.TypeOf((*MockDB)(nil).MarkNotificationViewed), ctx, notificationID, actorID)
}

// Migrate mocks base method.
func (m *MockDB) Migrate(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Migrate", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Migrate indicates an expected call of Migrate.
func (mr *MockDBMockRecorder) Migrate(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Migrate", reflect.TypeOf((*MockDB)(nil).Migrate), ctx)
}

// NewestConnectorVersionForId mocks base method.
func (m *MockDB) NewestConnectorVersionForId(ctx context.Context, id apid.ID) (*database.ConnectorVersion, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewestConnectorVersionForId", ctx, id)
	ret0, _ := ret[0].(*database.ConnectorVersion)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NewestConnectorVersionForId indicates an expected call of NewestConnectorVersionForId.
func (mr *MockDBMockRecorder) NewestConnectorVersionForId(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewestConnectorVersionForId", reflect.TypeOf((*MockDB)(nil).NewestConnectorVersionForId), ctx, id)
}

// NewestPublishedConnectorVersionForId mocks base method.
func (m *MockDB) NewestPublishedConnectorVersionForId(ctx context.Context, id apid.ID) (*database.ConnectorVersion, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewestPublishedConnectorVersionForId", ctx, id)
	ret0, _ := ret[0].(*database.ConnectorVersion)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NewestPublishedConnectorVersionForId indicates an expected call of NewestPublishedConnectorVersionForId.
func (mr *MockDBMockRecorder) NewestPublishedConnectorVersionForId(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewestPublishedConnectorVersionForId", reflect.TypeOf((*MockDB)(nil).NewestPublishedConnectorVersionForId), ctx, id)
}

// NotificationViewedMap mocks base method.
func (m *MockDB) NotificationViewedMap(ctx context.Context, actorID apid.ID, ids []apid.ID) (map[apid.ID]time.Time, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NotificationViewedMap", ctx, actorID, ids)
	ret0, _ := ret[0].(map[apid.ID]time.Time)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NotificationViewedMap indicates an expected call of NotificationViewedMap.
func (mr *MockDBMockRecorder) NotificationViewedMap(ctx, actorID, ids interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NotificationViewedMap", reflect.TypeOf((*MockDB)(nil).NotificationViewedMap), ctx, actorID, ids)
}

// Ping mocks base method.
func (m *MockDB) Ping(ctx context.Context) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ping", ctx)
	ret0, _ := ret[0].(bool)
	return ret0
}

// Ping indicates an expected call of Ping.
func (mr *MockDBMockRecorder) Ping(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ping", reflect.TypeOf((*MockDB)(nil).Ping), ctx)
}

// PurgeSoftDeletedRecords mocks base method.
func (m *MockDB) PurgeSoftDeletedRecords(ctx context.Context, olderThan time.Time) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PurgeSoftDeletedRecords", ctx, olderThan)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PurgeSoftDeletedRecords indicates an expected call of PurgeSoftDeletedRecords.
func (mr *MockDBMockRecorder) PurgeSoftDeletedRecords(ctx, olderThan interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PurgeSoftDeletedRecords", reflect.TypeOf((*MockDB)(nil).PurgeSoftDeletedRecords), ctx, olderThan)
}

// PutActorAnnotations mocks base method.
func (m *MockDB) PutActorAnnotations(ctx context.Context, id apid.ID, annotations map[string]string) (*database.Actor, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PutActorAnnotations", ctx, id, annotations)
	ret0, _ := ret[0].(*database.Actor)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PutActorAnnotations indicates an expected call of PutActorAnnotations.
func (mr *MockDBMockRecorder) PutActorAnnotations(ctx, id, annotations interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PutActorAnnotations", reflect.TypeOf((*MockDB)(nil).PutActorAnnotations), ctx, id, annotations)
}

// PutActorLabels mocks base method.
func (m *MockDB) PutActorLabels(ctx context.Context, id apid.ID, labels map[string]string) (*database.Actor, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PutActorLabels", ctx, id, labels)
	ret0, _ := ret[0].(*database.Actor)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PutActorLabels indicates an expected call of PutActorLabels.
func (mr *MockDBMockRecorder) PutActorLabels(ctx, id, labels interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PutActorLabels", reflect.TypeOf((*MockDB)(nil).PutActorLabels), ctx, id, labels)
}

// PutConnectionAnnotations mocks base method.
func (m *MockDB) PutConnectionAnnotations(ctx context.Context, id apid.ID, annotations map[string]string) (*database.Connection, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PutConnectionAnnotations", ctx, id, annotations)
	ret0, _ := ret[0].(*database.Connection)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PutConnectionAnnotations indicates an expected call of PutConnectionAnnotations.
func (mr *MockDBMockRecorder) PutConnectionAnnotations(ctx, id, annotations interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PutConnectionAnnotations", reflect.TypeOf((*MockDB)(nil).PutConnectionAnnotations), ctx, id, annotations)
}

// PutConnectionLabels mocks base method.
func (m *MockDB) PutConnectionLabels(ctx context.Context, id apid.ID, labels map[string]string) (*database.Connection, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PutConnectionLabels", ctx, id, labels)
	ret0, _ := ret[0].(*database.Connection)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PutConnectionLabels indicates an expected call of PutConnectionLabels.
func (mr *MockDBMockRecorder) PutConnectionLabels(ctx, id, labels interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PutConnectionLabels", reflect.TypeOf((*MockDB)(nil).PutConnectionLabels), ctx, id, labels)
}

// PutKeyAnnotations mocks base method.
func (m *MockDB) PutKeyAnnotations(ctx context.Context, id apid.ID, annotations map[string]string) (*database.Key, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PutKeyAnnotations", ctx, id, annotations)
	ret0, _ := ret[0].(*database.Key)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PutKeyAnnotations indicates an expected call of PutKeyAnnotations.
func (mr *MockDBMockRecorder) PutKeyAnnotations(ctx, id, annotations interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PutKeyAnnotations", reflect.TypeOf((*MockDB)(nil).PutKeyAnnotations), ctx, id, annotations)
}

// PutKeyLabels mocks base method.
func (m *MockDB) PutKeyLabels(ctx context.Context, id apid.ID, labels map[string]string) (*database.Key, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PutKeyLabels", ctx, id, labels)
	ret0, _ := ret[0].(*database.Key)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PutKeyLabels indicates an expected call of PutKeyLabels.
func (mr *MockDBMockRecorder) PutKeyLabels(ctx, id, labels interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PutKeyLabels", reflect.TypeOf((*MockDB)(nil).PutKeyLabels), ctx, id, labels)
}

// PutNamespaceAnnotations mocks base method.
func (m *MockDB) PutNamespaceAnnotations(ctx context.Context, path string, annotations map[string]string) (*database.Namespace, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PutNamespaceAnnotations", ctx, path, annotations)
	ret0, _ := ret[0].(*database.Namespace)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PutNamespaceAnnotations indicates an expected call of PutNamespaceAnnotations.
func (mr *MockDBMockRecorder) PutNamespaceAnnotations(ctx, path, annotations interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PutNamespaceAnnotations", reflect.TypeOf((*MockDB)(nil).PutNamespaceAnnotations), ctx, path, annotations)
}

// PutNamespaceLabels mocks base method.
func (m *MockDB) PutNamespaceLabels(ctx context.Context, path string, labels map[string]string) (*database.Namespace, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PutNamespaceLabels", ctx, path, labels)
	ret0, _ := ret[0].(*database.Namespace)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PutNamespaceLabels indicates an expected call of PutNamespaceLabels.
func (mr *MockDBMockRecorder) PutNamespaceLabels(ctx, path, labels interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PutNamespaceLabels", reflect.TypeOf((*MockDB)(nil).PutNamespaceLabels), ctx, path, labels)
}

// PutRateLimitAnnotations mocks base method.
func (m *MockDB) PutRateLimitAnnotations(ctx context.Context, id apid.ID, annotations map[string]string) (*database.RateLimit, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PutRateLimitAnnotations", ctx, id, annotations)
	ret0, _ := ret[0].(*database.RateLimit)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PutRateLimitAnnotations indicates an expected call of PutRateLimitAnnotations.
func (mr *MockDBMockRecorder) PutRateLimitAnnotations(ctx, id, annotations interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PutRateLimitAnnotations", reflect.TypeOf((*MockDB)(nil).PutRateLimitAnnotations), ctx, id, annotations)
}

// PutRateLimitLabels mocks base method.
func (m *MockDB) PutRateLimitLabels(ctx context.Context, id apid.ID, labels map[string]string) (*database.RateLimit, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PutRateLimitLabels", ctx, id, labels)
	ret0, _ := ret[0].(*database.RateLimit)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PutRateLimitLabels indicates an expected call of PutRateLimitLabels.
func (mr *MockDBMockRecorder) PutRateLimitLabels(ctx, id, labels interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PutRateLimitLabels", reflect.TypeOf((*MockDB)(nil).PutRateLimitLabels), ctx, id, labels)
}

// ReconcileCarryForwardLabels mocks base method.
func (m *MockDB) ReconcileCarryForwardLabels(ctx context.Context, batchSize int32, limiter *rate.Limiter) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReconcileCarryForwardLabels", ctx, batchSize, limiter)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReconcileCarryForwardLabels indicates an expected call of ReconcileCarryForwardLabels.
func (mr *MockDBMockRecorder) ReconcileCarryForwardLabels(ctx, batchSize, limiter interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReconcileCarryForwardLabels", reflect.TypeOf((*MockDB)(nil).ReconcileCarryForwardLabels), ctx, batchSize, limiter)
}

// RefreshConnectionsForConnectorVersion mocks base method.
func (m *MockDB) RefreshConnectionsForConnectorVersion(ctx context.Context, id apid.ID, version uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RefreshConnectionsForConnectorVersion", ctx, id, version)
	ret0, _ := ret[0].(error)
	return ret0
}

// RefreshConnectionsForConnectorVersion indicates an expected call of RefreshConnectionsForConnectorVersion.
func (mr *MockDBMockRecorder) RefreshConnectionsForConnectorVersion(ctx, id, version interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RefreshConnectionsForConnectorVersion", reflect.TypeOf((*MockDB)(nil).RefreshConnectionsForConnectorVersion), ctx, id, version)
}

// RefreshNamespaceLabelsCarryForward mocks base method.
func (m *MockDB) RefreshNamespaceLabelsCarryForward(ctx context.Context, nsPath string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RefreshNamespaceLabelsCarryForward", ctx, nsPath)
	ret0, _ := ret[0].(error)
	return ret0
}

// RefreshNamespaceLabelsCarryForward indicates an expected call of RefreshNamespaceLabelsCarryForward.
func (mr *MockDBMockRecorder) RefreshNamespaceLabelsCarryForward(ctx, nsPath interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RefreshNamespaceLabelsCarryForward", reflect.TypeOf((*MockDB)(nil).RefreshNamespaceLabelsCarryForward), ctx, nsPath)
}

// ResolveNotificationsForResource mocks base method.
func (m *MockDB) ResolveNotificationsForResource(ctx context.Context, resourceType string, resourceID apid.ID, source string, keepKeys []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResolveNotificationsForResource", ctx, resourceType, resourceID, source, keepKeys)
	ret0, _ := ret[0].(error)
	return ret0
}

// ResolveNotificationsForResource indicates an expected call of ResolveNotificationsForResource.
func (mr *MockDBMockRecorder) ResolveNotificationsForResource(ctx, resourceType, resourceID, source, keepKeys interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResolveNotificationsForResource", reflect.TypeOf((*MockDB)(nil).ResolveNotificationsForResource), ctx, resourceType, resourceID, source, keepKeys)
}

// SetConnectionEncryptedConfiguration mocks base method.
func (m *MockDB) SetConnectionEncryptedConfiguration(ctx context.Context, id apid.ID, encryptedConfig *encfield.EncryptedField) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetConnectionEncryptedConfiguration", ctx, id, encryptedConfig)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetConnectionEncryptedConfiguration indicates an expected call of SetConnectionEncryptedConfiguration.
func (mr *MockDBMockRecorder) SetConnectionEncryptedConfiguration(ctx, id, encryptedConfig interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetConnectionEncryptedConfiguration", reflect.TypeOf((*MockDB)(nil).SetConnectionEncryptedConfiguration), ctx, id, encryptedConfig)
}

// SetConnectionHealthState mocks base method.
func (m *MockDB) SetConnectionHealthState(ctx context.Context, id apid.ID, state database.ConnectionHealthState) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetConnectionHealthState", ctx, id, state)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetConnectionHealthState indicates an expected call of SetConnectionHealthState.
func (mr *MockDBMockRecorder) SetConnectionHealthState(ctx, id, state interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetConnectionHealthState", reflect.TypeOf((*MockDB)(nil).SetConnectionHealthState), ctx, id, state)
}

// SetConnectionSetupError mocks base method.
func (m *MockDB) SetConnectionSetupError(ctx context.Context, id apid.ID, setupError *string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetConnectionSetupError", ctx, id, setupError)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetConnectionSetupError indicates an expected call of SetConnectionSetupError.
func (mr *MockDBMockRecorder) SetConnectionSetupError(ctx, id, setupError interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetConnectionSetupError", reflect.TypeOf((*MockDB)(nil).SetConnectionSetupError), ctx, id, setupError)
}

// SetConnectionSetupStep mocks base method.
func (m *MockDB) SetConnectionSetupStep(ctx context.Context, id apid.ID, setupStep *connectors.SetupStep) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetConnectionSetupStep", ctx, id, setupStep)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetConnectionSetupStep indicates an expected call of SetConnectionSetupStep.
func (mr *MockDBMockRecorder) SetConnectionSetupStep(ctx, id, setupStep interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetConnectionSetupStep", reflect.TypeOf((*MockDB)(nil).SetConnectionSetupStep), ctx, id, setupStep)
}

// SetConnectionState mocks base method.
func (m *MockDB) SetConnectionState(ctx context.Context, id apid.ID, state database.ConnectionState) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetConnectionState", ctx, id, state)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetConnectionState indicates an expected call of SetConnectionState.
func (mr *MockDBMockRecorder) SetConnectionState(ctx, id, state interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetConnectionState", reflect.TypeOf((*MockDB)(nil).SetConnectionState), ctx, id, state)
}

// SetConnectorVersionState mocks base method.
func (m *MockDB) SetConnectorVersionState(ctx context.Context, id apid.ID, version uint64, state database.ConnectorVersionState) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetConnectorVersionState", ctx, id, version, state)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetConnectorVersionState indicates an expected call of SetConnectorVersionState.
func (mr *MockDBMockRecorder) SetConnectorVersionState(ctx, id, version, state interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetConnectorVersionState", reflect.TypeOf((*MockDB)(nil).SetConnectorVersionState), ctx, id, version, state)
}

// SetCursorEncryptor mocks base method.
func (m *MockDB) SetCursorEncryptor(e pagination.CursorEncryptor) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetCursorEncryptor", e)
}

// SetCursorEncryptor indicates an expected call of SetCursorEncryptor.
func (mr *MockDBMockRecorder) SetCursorEncryptor(e interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetCursorEncryptor", reflect.TypeOf((*MockDB)(nil).SetCursorEncryptor), e)
}

// SetDataEncryptionKeyCurrentFlag mocks base method.
func (m *MockDB) SetDataEncryptionKeyCurrentFlag(ctx context.Context, id apid.ID, isCurrent bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetDataEncryptionKeyCurrentFlag", ctx, id, isCurrent)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetDataEncryptionKeyCurrentFlag indicates an expected call of SetDataEncryptionKeyCurrentFlag.
func (mr *MockDBMockRecorder) SetDataEncryptionKeyCurrentFlag(ctx, id, isCurrent interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetDataEncryptionKeyCurrentFlag", reflect.TypeOf((*MockDB)(nil).SetDataEncryptionKeyCurrentFlag), ctx, id, isCurrent)
}

// SetKeyState mocks base method.
func (m *MockDB) SetKeyState(ctx context.Context, id apid.ID, state database.KeyState) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetKeyState", ctx, id, state)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetKeyState indicates an expected call of SetKeyState.
func (mr *MockDBMockRecorder) SetKeyState(ctx, id, state interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetKeyState", reflect.TypeOf((*MockDB)(nil).SetKeyState), ctx, id, state)
}

// SetNamespaceKeyId mocks base method.
func (m *MockDB) SetNamespaceKeyId(ctx context.Context, path string, ekId *apid.ID) (*database.Namespace, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetNamespaceKeyId", ctx, path, ekId)
	ret0, _ := ret[0].(*database.Namespace)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetNamespaceKeyId indicates an expected call of SetNamespaceKeyId.
func (mr *MockDBMockRecorder) SetNamespaceKeyId(ctx, path, ekId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetNamespaceKeyId", reflect.TypeOf((*MockDB)(nil).SetNamespaceKeyId), ctx, path, ekId)
}

// SetNamespaceState mocks base method.
func (m *MockDB) SetNamespaceState(ctx context.Context, path string, state database.NamespaceState) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetNamespaceState", ctx, path, state)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetNamespaceState indicates an expected call of SetNamespaceState.
func (mr *MockDBMockRecorder) SetNamespaceState(ctx, path, state interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetNamespaceState", reflect.TypeOf((*MockDB)(nil).SetNamespaceState), ctx, path, state)
}

// UpdateActorAnnotations mocks base method.
func (m *MockDB) UpdateActorAnnotations(ctx context.Context, id apid.ID, annotations map[string]string) (*database.Actor, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateActorAnnotations", ctx, id, annotations)
	ret0, _ := ret[0].(*database.Actor)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateActorAnnotations indicates an expected call of UpdateActorAnnotations.
func (mr *MockDBMockRecorder) UpdateActorAnnotations(ctx, id, annotations interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateActorAnnotations", reflect.TypeOf((*MockDB)(nil).UpdateActorAnnotations), ctx, id, annotations)
}

// UpdateApiKeyCredentialLastValidated mocks base method.
func (m *MockDB) UpdateApiKeyCredentialLastValidated(ctx context.Context, credentialId apid.ID, at time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateApiKeyCredentialLastValidated", ctx, credentialId, at)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateApiKeyCredentialLastValidated indicates an expected call of UpdateApiKeyCredentialLastValidated.
func (mr *MockDBMockRecorder) UpdateApiKeyCredentialLastValidated(ctx, credentialId, at interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateApiKeyCredentialLastValidated", reflect.TypeOf((*MockDB)(nil).UpdateApiKeyCredentialLastValidated), ctx, credentialId, at)
}

// UpdateConnectionAnnotations mocks base method.
func (m *MockDB) UpdateConnectionAnnotations(ctx context.Context, id apid.ID, annotations map[string]string) (*database.Connection, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateConnectionAnnotations", ctx, id, annotations)
	ret0, _ := ret[0].(*database.Connection)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateConnectionAnnotations indicates an expected call of UpdateConnectionAnnotations.
func (mr *MockDBMockRecorder) UpdateConnectionAnnotations(ctx, id, annotations interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateConnectionAnnotations", reflect.TypeOf((*MockDB)(nil).UpdateConnectionAnnotations), ctx, id, annotations)
}

// UpdateConnectionForVersionMigration mocks base method.
func (m *MockDB) UpdateConnectionForVersionMigration(ctx context.Context, update database.ConnectionVersionMigrationUpdate) (*database.Connection, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateConnectionForVersionMigration", ctx, update)
	ret0, _ := ret[0].(*database.Connection)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateConnectionForVersionMigration indicates an expected call of UpdateConnectionForVersionMigration.
func (mr *MockDBMockRecorder) UpdateConnectionForVersionMigration(ctx, update interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateConnectionForVersionMigration", reflect.TypeOf((*MockDB)(nil).UpdateConnectionForVersionMigration), ctx, update)
}

// UpdateConnectionLabels mocks base method.
func (m *MockDB) UpdateConnectionLabels(ctx context.Context, id apid.ID, labels map[string]string) (*database.Connection, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateConnectionLabels", ctx, id, labels)
	ret0, _ := ret[0].(*database.Connection)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateConnectionLabels indicates an expected call of UpdateConnectionLabels.
func (mr *MockDBMockRecorder) UpdateConnectionLabels(ctx, id, labels interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateConnectionLabels", reflect.TypeOf((*MockDB)(nil).UpdateConnectionLabels), ctx, id, labels)
}

// UpdateDataEncryptionKeyWrapping mocks base method.
func (m *MockDB) UpdateDataEncryptionKeyWrapping(ctx context.Context, dek *database.DataEncryptionKey) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateDataEncryptionKeyWrapping", ctx, dek)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateDataEncryptionKeyWrapping indicates an expected call of UpdateDataEncryptionKeyWrapping.
func (mr *MockDBMockRecorder) UpdateDataEncryptionKeyWrapping(ctx, dek interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateDataEncryptionKeyWrapping", reflect.TypeOf((*MockDB)(nil).UpdateDataEncryptionKeyWrapping), ctx, dek)
}

// UpdateKey mocks base method.
func (m *MockDB) UpdateKey(ctx context.Context, id apid.ID, updates map[string]interface{}) (*database.Key, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateKey", ctx, id, updates)
	ret0, _ := ret[0].(*database.Key)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateKey indicates an expected call of UpdateKey.
func (mr *MockDBMockRecorder) UpdateKey(ctx, id, updates interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateKey", reflect.TypeOf((*MockDB)(nil).UpdateKey), ctx, id, updates)
}

// UpdateKeyAnnotations mocks base method.
func (m *MockDB) UpdateKeyAnnotations(ctx context.Context, id apid.ID, annotations map[string]string) (*database.Key, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateKeyAnnotations", ctx, id, annotations)
	ret0, _ := ret[0].(*database.Key)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateKeyAnnotations indicates an expected call of UpdateKeyAnnotations.
func (mr *MockDBMockRecorder) UpdateKeyAnnotations(ctx, id, annotations interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateKeyAnnotations", reflect.TypeOf((*MockDB)(nil).UpdateKeyAnnotations), ctx, id, annotations)
}

// UpdateKeyLabels mocks base method.
func (m *MockDB) UpdateKeyLabels(ctx context.Context, id apid.ID, labels map[string]string) (*database.Key, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateKeyLabels", ctx, id, labels)
	ret0, _ := ret[0].(*database.Key)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateKeyLabels indicates an expected call of UpdateKeyLabels.
func (mr *MockDBMockRecorder) UpdateKeyLabels(ctx, id, labels interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateKeyLabels", reflect.TypeOf((*MockDB)(nil).UpdateKeyLabels), ctx, id, labels)
}

// UpdateNamespaceAnnotations mocks base method.
func (m *MockDB) UpdateNamespaceAnnotations(ctx context.Context, path string, annotations map[string]string) (*database.Namespace, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateNamespaceAnnotations", ctx, path, annotations)
	ret0, _ := ret[0].(*database.Namespace)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateNamespaceAnnotations indicates an expected call of UpdateNamespaceAnnotations.
func (mr *MockDBMockRecorder) UpdateNamespaceAnnotations(ctx, path, annotations interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateNamespaceAnnotations", reflect.TypeOf((*MockDB)(nil).UpdateNamespaceAnnotations), ctx, path, annotations)
}

// UpdateNamespaceLabels mocks base method.
func (m *MockDB) UpdateNamespaceLabels(ctx context.Context, path string, labels map[string]string) (*database.Namespace, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateNamespaceLabels", ctx, path, labels)
	ret0, _ := ret[0].(*database.Namespace)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateNamespaceLabels indicates an expected call of UpdateNamespaceLabels.
func (mr *MockDBMockRecorder) UpdateNamespaceLabels(ctx, path, labels interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateNamespaceLabels", reflect.TypeOf((*MockDB)(nil).UpdateNamespaceLabels), ctx, path, labels)
}

// UpdateRateLimitAnnotations mocks base method.
func (m *MockDB) UpdateRateLimitAnnotations(ctx context.Context, id apid.ID, annotations map[string]string) (*database.RateLimit, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateRateLimitAnnotations", ctx, id, annotations)
	ret0, _ := ret[0].(*database.RateLimit)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateRateLimitAnnotations indicates an expected call of UpdateRateLimitAnnotations.
func (mr *MockDBMockRecorder) UpdateRateLimitAnnotations(ctx, id, annotations interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateRateLimitAnnotations", reflect.TypeOf((*MockDB)(nil).UpdateRateLimitAnnotations), ctx, id, annotations)
}

// UpdateRateLimitDefinition mocks base method.
func (m *MockDB) UpdateRateLimitDefinition(ctx context.Context, id apid.ID, def rate_limit.RateLimit) (*database.RateLimit, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateRateLimitDefinition", ctx, id, def)
	ret0, _ := ret[0].(*database.RateLimit)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateRateLimitDefinition indicates an expected call of UpdateRateLimitDefinition.
func (mr *MockDBMockRecorder) UpdateRateLimitDefinition(ctx, id, def interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateRateLimitDefinition", reflect.TypeOf((*MockDB)(nil).UpdateRateLimitDefinition), ctx, id, def)
}

// UpdateRateLimitLabels mocks base method.
func (m *MockDB) UpdateRateLimitLabels(ctx context.Context, id apid.ID, labels map[string]string) (*database.RateLimit, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateRateLimitLabels", ctx, id, labels)
	ret0, _ := ret[0].(*database.RateLimit)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateRateLimitLabels indicates an expected call of UpdateRateLimitLabels.
func (mr *MockDBMockRecorder) UpdateRateLimitLabels(ctx, id, labels interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateRateLimitLabels", reflect.TypeOf((*MockDB)(nil).UpdateRateLimitLabels), ctx, id, labels)
}

// UpsertActor mocks base method.
func (m *MockDB) UpsertActor(ctx context.Context, actor database.IActorData) (*database.Actor, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertActor", ctx, actor)
	ret0, _ := ret[0].(*database.Actor)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpsertActor indicates an expected call of UpsertActor.
func (mr *MockDBMockRecorder) UpsertActor(ctx, actor interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertActor", reflect.TypeOf((*MockDB)(nil).UpsertActor), ctx, actor)
}

// UpsertConnectorVersion mocks base method.
func (m *MockDB) UpsertConnectorVersion(ctx context.Context, cv *database.ConnectorVersion) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertConnectorVersion", ctx, cv)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertConnectorVersion indicates an expected call of UpsertConnectorVersion.
func (mr *MockDBMockRecorder) UpsertConnectorVersion(ctx, cv interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertConnectorVersion", reflect.TypeOf((*MockDB)(nil).UpsertConnectorVersion), ctx, cv)
}

// UpsertNotification mocks base method.
func (m *MockDB) UpsertNotification(ctx context.Context, upsert database.NotificationUpsert) (*database.Notification, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertNotification", ctx, upsert)
	ret0, _ := ret[0].(*database.Notification)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpsertNotification indicates an expected call of UpsertNotification.
func (mr *MockDBMockRecorder) UpsertNotification(ctx, upsert interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertNotification", reflect.TypeOf((*MockDB)(nil).UpsertNotification), ctx, upsert)
}
