// Code generated by MockGen. DO NOT EDIT.
// Source: ./interface.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"
	time "time"

	gomock "github.com/golang/mock/gomock"
	apid "github.com/rmorlok/authproxy/internal/apid"
	database "github.com/rmorlok/authproxy/internal/database"
	encfield "github.com/rmorlok/authproxy/internal/encfield"
	auth "github.com/rmorlok/authproxy/internal/schema/auth"
	pagination "github.com/rmorlok/authproxy/internal/util/pagination"
)

// MockIActorData is a mock of IActorData interface.
type MockIActorData struct {
	ctrl     *gomock.Controller
	recorder *MockIActorDataMockRecorder
}

// MockIActorDataMockRecorder is the mock recorder for MockIActorData.
type MockIActorDataMockRecorder struct {
	mock *MockIActorData
}

// NewMockIActorData creates a new mock instance.
func NewMockIActorData(ctrl *gomock.Controller) *MockIActorData {
	mock := &MockIActorData{ctrl: ctrl}
	mock.recorder = &MockIActorDataMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIActorData) EXPECT() *MockIActorDataMockRecorder {
	return m.recorder
}

// GetExternalId mocks base method.
func (m *MockIActorData) GetExternalId() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetExternalId")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetExternalId indicates an expected call of GetExternalId.
func (mr *MockIActorDataMockRecorder) GetExternalId() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetExternalId", reflect.TypeOf((*MockIActorData)(nil).GetExternalId))
}

// GetId mocks base method.
func (m *MockIActorData) GetId() apid.ID {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetId")
	ret0, _ := ret[0].(apid.ID)
	return ret0
}

// GetId indicates an expected call of GetId.
func (mr *MockIActorDataMockRecorder) GetId() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetId", reflect.TypeOf((*MockIActorData)(nil).GetId))
}

// GetLabels mocks base method.
func (m *MockIActorData) GetLabels() map[string]string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLabels")
	ret0, _ := ret[0].(map[string]string)
	return ret0
}

// GetLabels indicates an expected call of GetLabels.
func (mr *MockIActorDataMockRecorder) GetLabels() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLabels", reflect.TypeOf((*MockIActorData)(nil).GetLabels))
}

// GetNamespace mocks base method.
func (m *MockIActorData) GetNamespace() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNamespace")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetNamespace indicates an expected call of GetNamespace.
func (mr *MockIActorDataMockRecorder) GetNamespace() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNamespace", reflect.TypeOf((*MockIActorData)(nil).GetNamespace))
}

// GetPermissions mocks base method.
func (m *MockIActorData) GetPermissions() []auth.Permission {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPermissions")
	ret0, _ := ret[0].([]auth.Permission)
	return ret0
}

// GetPermissions indicates an expected call of GetPermissions.
func (mr *MockIActorDataMockRecorder) GetPermissions() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPermissions", reflect.TypeOf((*MockIActorData)(nil).GetPermissions))
}

// MockIActorDataExtended is a mock of IActorDataExtended interface.
type MockIActorDataExtended struct {
	ctrl     *gomock.Controller
	recorder *MockIActorDataExtendedMockRecorder
}

// MockIActorDataExtendedMockRecorder is the mock recorder for MockIActorDataExtended.
type MockIActorDataExtendedMockRecorder struct {
	mock *MockIActorDataExtended
}

// NewMockIActorDataExtended creates a new mock instance.
func NewMockIActorDataExtended(ctrl *gomock.Controller) *MockIActorDataExtended {
	mock := &MockIActorDataExtended{ctrl: ctrl}
	mock.recorder = &MockIActorDataExtendedMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIActorDataExtended) EXPECT() *MockIActorDataExtendedMockRecorder {
	return m.recorder
}

// GetEncryptedKey mocks base method.
func (m *MockIActorDataExtended) GetEncryptedKey() *encfield.EncryptedField {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEncryptedKey")
	ret0, _ := ret[0].(*encfield.EncryptedField)
	return ret0
}

// GetEncryptedKey indicates an expected call of GetEncryptedKey.
func (mr *MockIActorDataExtendedMockRecorder) GetEncryptedKey() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEncryptedKey", reflect.TypeOf((*MockIActorDataExtended)(nil).GetEncryptedKey))
}

// GetExternalId mocks base method.
func (m *MockIActorDataExtended) GetExternalId() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetExternalId")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetExternalId indicates an expected call of GetExternalId.
func (mr *MockIActorDataExtendedMockRecorder) GetExternalId() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetExternalId", reflect.TypeOf((*MockIActorDataExtended)(nil).GetExternalId))
}

// GetId mocks base method.
func (m *MockIActorDataExtended) GetId() apid.ID {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetId")
	ret0, _ := ret[0].(apid.ID)
	return ret0
}

// GetId indicates an expected call of GetId.
func (mr *MockIActorDataExtendedMockRecorder) GetId() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetId", reflect.TypeOf((*MockIActorDataExtended)(nil).GetId))
}

// GetLabels mocks base method.
func (m *MockIActorDataExtended) GetLabels() map[string]string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLabels")
	ret0, _ := ret[0].(map[string]string)
	return ret0
}

// GetLabels indicates an expected call of GetLabels.
func (mr *MockIActorDataExtendedMockRecorder) GetLabels() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLabels", reflect.TypeOf((*MockIActorDataExtended)(nil).GetLabels))
}

// GetNamespace mocks base method.
func (m *MockIActorDataExtended) GetNamespace() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNamespace")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetNamespace indicates an expected call of GetNamespace.
func (mr *MockIActorDataExtendedMockRecorder) GetNamespace() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNamespace", reflect.TypeOf((*MockIActorDataExtended)(nil).GetNamespace))
}

// GetPermissions mocks base method.
func (m *MockIActorDataExtended) GetPermissions() []auth.Permission {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPermissions")
	ret0, _ := ret[0].([]auth.Permission)
	return ret0
}

// GetPermissions indicates an expected call of GetPermissions.
func (mr *MockIActorDataExtendedMockRecorder) GetPermissions() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPermissions", reflect.TypeOf((*MockIActorDataExtended)(nil).GetPermissions))
}

// MockDB is a mock of DB interface.
type MockDB struct {
	ctrl     *gomock.Controller
	recorder *MockDBMockRecorder
}

// MockDBMockRecorder is the mock recorder for MockDB.
type MockDBMockRecorder struct {
	mock *MockDB
}

// NewMockDB creates a new mock instance.
func NewMockDB(ctrl *gomock.Controller) *MockDB {
	mock := &MockDB{ctrl: ctrl}
	mock.recorder = &MockDBMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDB) EXPECT() *MockDBMockRecorder {
	return m.recorder
}

// BatchUpdateReEncryptedFields mocks base method.
func (m *MockDB) BatchUpdateReEncryptedFields(ctx context.Context, updates []database.ReEncryptedFieldUpdate) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchUpdateReEncryptedFields", ctx, updates)
	ret0, _ := ret[0].(error)
	return ret0
}

// BatchUpdateReEncryptedFields indicates an expected call of BatchUpdateReEncryptedFields.
func (mr *MockDBMockRecorder) BatchUpdateReEncryptedFields(ctx, updates interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchUpdateReEncryptedFields", reflect.TypeOf((*MockDB)(nil).BatchUpdateReEncryptedFields), ctx, updates)
}

// CheckNonceValidAndMarkUsed mocks base method.
func (m *MockDB) CheckNonceValidAndMarkUsed(ctx context.Context, nonce apid.ID, retainRecordUntil time.Time) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckNonceValidAndMarkUsed", ctx, nonce, retainRecordUntil)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckNonceValidAndMarkUsed indicates an expected call of CheckNonceValidAndMarkUsed.
func (mr *MockDBMockRecorder) CheckNonceValidAndMarkUsed(ctx, nonce, retainRecordUntil interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckNonceValidAndMarkUsed", reflect.TypeOf((*MockDB)(nil).CheckNonceValidAndMarkUsed), ctx, nonce, retainRecordUntil)
}

// ClearCurrentFlagForEncryptionKey mocks base method.
func (m *MockDB) ClearCurrentFlagForEncryptionKey(ctx context.Context, encryptionKeyId apid.ID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClearCurrentFlagForEncryptionKey", ctx, encryptionKeyId)
	ret0, _ := ret[0].(error)
	return ret0
}

// ClearCurrentFlagForEncryptionKey indicates an expected call of ClearCurrentFlagForEncryptionKey.
func (mr *MockDBMockRecorder) ClearCurrentFlagForEncryptionKey(ctx, encryptionKeyId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClearCurrentFlagForEncryptionKey", reflect.TypeOf((*MockDB)(nil).ClearCurrentFlagForEncryptionKey), ctx, encryptionKeyId)
}

// ClearCurrentFlagForNamespace mocks base method.
func (m *MockDB) ClearCurrentFlagForNamespace(ctx context.Context, namespacePath string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClearCurrentFlagForNamespace", ctx, namespacePath)
	ret0, _ := ret[0].(error)
	return ret0
}

// ClearCurrentFlagForNamespace indicates an expected call of ClearCurrentFlagForNamespace.
func (mr *MockDBMockRecorder) ClearCurrentFlagForNamespace(ctx, namespacePath interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClearCurrentFlagForNamespace", reflect.TypeOf((*MockDB)(nil).ClearCurrentFlagForNamespace), ctx, namespacePath)
}

// CreateActor mocks base method.
func (m *MockDB) CreateActor(ctx context.Context, actor *database.Actor) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateActor", ctx, actor)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateActor indicates an expected call of CreateActor.
func (mr *MockDBMockRecorder) CreateActor(ctx, actor interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateActor", reflect.TypeOf((*MockDB)(nil).CreateActor), ctx, actor)
}

// CreateConnection mocks base method.
func (m *MockDB) CreateConnection(ctx context.Context, c *database.Connection) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateConnection", ctx, c)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateConnection indicates an expected call of CreateConnection.
func (mr *MockDBMockRecorder) CreateConnection(ctx, c interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateConnection", reflect.TypeOf((*MockDB)(nil).CreateConnection), ctx, c)
}

// CreateEncryptionKey mocks base method.
func (m *MockDB) CreateEncryptionKey(ctx context.Context, ek *database.EncryptionKey) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateEncryptionKey", ctx, ek)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateEncryptionKey indicates an expected call of CreateEncryptionKey.
func (mr *MockDBMockRecorder) CreateEncryptionKey(ctx, ek interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateEncryptionKey", reflect.TypeOf((*MockDB)(nil).CreateEncryptionKey), ctx, ek)
}

// CreateEncryptionKeyVersion mocks base method.
func (m *MockDB) CreateEncryptionKeyVersion(ctx context.Context, ekv *database.EncryptionKeyVersion) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateEncryptionKeyVersion", ctx, ekv)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateEncryptionKeyVersion indicates an expected call of CreateEncryptionKeyVersion.
func (mr *MockDBMockRecorder) CreateEncryptionKeyVersion(ctx, ekv interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateEncryptionKeyVersion", reflect.TypeOf((*MockDB)(nil).CreateEncryptionKeyVersion), ctx, ekv)
}

// CreateNamespace mocks base method.
func (m *MockDB) CreateNamespace(ctx context.Context, ns *database.Namespace) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateNamespace", ctx, ns)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateNamespace indicates an expected call of CreateNamespace.
func (mr *MockDBMockRecorder) CreateNamespace(ctx, ns interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateNamespace", reflect.TypeOf((*MockDB)(nil).CreateNamespace), ctx, ns)
}

// DeleteActor mocks base method.
func (m *MockDB) DeleteActor(ctx context.Context, id apid.ID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteActor", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteActor indicates an expected call of DeleteActor.
func (mr *MockDBMockRecorder) DeleteActor(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteActor", reflect.TypeOf((*MockDB)(nil).DeleteActor), ctx, id)
}

// DeleteActorAnnotations mocks base method.
func (m *MockDB) DeleteActorAnnotations(ctx context.Context, id apid.ID, keys []string) (*database.Actor, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteActorAnnotations", ctx, id, keys)
	ret0, _ := ret[0].(*database.Actor)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteActorAnnotations indicates an expected call of DeleteActorAnnotations.
func (mr *MockDBMockRecorder) DeleteActorAnnotations(ctx, id, keys interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteActorAnnotations", reflect.TypeOf((*MockDB)(nil).DeleteActorAnnotations), ctx, id, keys)
}

// DeleteActorLabels mocks base method.
func (m *MockDB) DeleteActorLabels(ctx context.Context, id apid.ID, keys []string) (*database.Actor, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteActorLabels", ctx, id, keys)
	ret0, _ := ret[0].(*database.Actor)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteActorLabels indicates an expected call of DeleteActorLabels.
func (mr *MockDBMockRecorder) DeleteActorLabels(ctx, id, keys interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteActorLabels", reflect.TypeOf((*MockDB)(nil).DeleteActorLabels), ctx, id, keys)
}

// DeleteAllOAuth2TokensForConnection mocks base method.
func (m *MockDB) DeleteAllOAuth2TokensForConnection(ctx context.Context, connectionId apid.ID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAllOAuth2TokensForConnection", ctx, connectionId)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAllOAuth2TokensForConnection indicates an expected call of DeleteAllOAuth2TokensForConnection.
func (mr *MockDBMockRecorder) DeleteAllOAuth2TokensForConnection(ctx, connectionId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAllOAuth2TokensForConnection", reflect.TypeOf((*MockDB)(nil).DeleteAllOAuth2TokensForConnection), ctx, connectionId)
}

// DeleteConnection mocks base method.
func (m *MockDB) DeleteConnection(ctx context.Context, id apid.ID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteConnection", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteConnection indicates an expected call of DeleteConnection.
func (mr *MockDBMockRecorder) DeleteConnection(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteConnection", reflect.TypeOf((*MockDB)(nil).DeleteConnection), ctx, id)
}

// DeleteConnectionAnnotations mocks base method.
func (m *MockDB) DeleteConnectionAnnotations(ctx context.Context, id apid.ID, keys []string) (*database.Connection, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteConnectionAnnotations", ctx, id, keys)
	ret0, _ := ret[0].(*database.Connection)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteConnectionAnnotations indicates an expected call of DeleteConnectionAnnotations.
func (mr *MockDBMockRecorder) DeleteConnectionAnnotations(ctx, id, keys interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteConnectionAnnotations", reflect.TypeOf((*MockDB)(nil).DeleteConnectionAnnotations), ctx, id, keys)
}

// DeleteConnectionLabels mocks base method.
func (m *MockDB) DeleteConnectionLabels(ctx context.Context, id apid.ID, keys []string) (*database.Connection, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteConnectionLabels", ctx, id, keys)
	ret0, _ := ret[0].(*database.Connection)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteConnectionLabels indicates an expected call of DeleteConnectionLabels.
func (mr *MockDBMockRecorder) DeleteConnectionLabels(ctx, id, keys interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteConnectionLabels", reflect.TypeOf((*MockDB)(nil).DeleteConnectionLabels), ctx, id, keys)
}

// DeleteEncryptionKey mocks base method.
func (m *MockDB) DeleteEncryptionKey(ctx context.Context, id apid.ID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteEncryptionKey", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteEncryptionKey indicates an expected call of DeleteEncryptionKey.
func (mr *MockDBMockRecorder) DeleteEncryptionKey(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteEncryptionKey", reflect.TypeOf((*MockDB)(nil).DeleteEncryptionKey), ctx, id)
}

// DeleteEncryptionKeyAnnotations mocks base method.
func (m *MockDB) DeleteEncryptionKeyAnnotations(ctx context.Context, id apid.ID, keys []string) (*database.EncryptionKey, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteEncryptionKeyAnnotations", ctx, id, keys)
	ret0, _ := ret[0].(*database.EncryptionKey)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteEncryptionKeyAnnotations indicates an expected call of DeleteEncryptionKeyAnnotations.
func (mr *MockDBMockRecorder) DeleteEncryptionKeyAnnotations(ctx, id, keys interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteEncryptionKeyAnnotations", reflect.TypeOf((*MockDB)(nil).DeleteEncryptionKeyAnnotations), ctx, id, keys)
}

// DeleteEncryptionKeyLabels mocks base method.
func (m *MockDB) DeleteEncryptionKeyLabels(ctx context.Context, id apid.ID, keys []string) (*database.EncryptionKey, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteEncryptionKeyLabels", ctx, id, keys)
	ret0, _ := ret[0].(*database.EncryptionKey)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteEncryptionKeyLabels indicates an expected call of DeleteEncryptionKeyLabels.
func (mr *MockDBMockRecorder) DeleteEncryptionKeyLabels(ctx, id, keys interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteEncryptionKeyLabels", reflect.TypeOf((*MockDB)(nil).DeleteEncryptionKeyLabels), ctx, id, keys)
}

// DeleteEncryptionKeyVersion mocks base method.
func (m *MockDB) DeleteEncryptionKeyVersion(ctx context.Context, id apid.ID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteEncryptionKeyVersion", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteEncryptionKeyVersion indicates an expected call of DeleteEncryptionKeyVersion.
func (mr *MockDBMockRecorder) DeleteEncryptionKeyVersion(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteEncryptionKeyVersion", reflect.TypeOf((*MockDB)(nil).DeleteEncryptionKeyVersion), ctx, id)
}

// DeleteEncryptionKeyVersionsForEncryptionKey mocks base method.
func (m *MockDB) DeleteEncryptionKeyVersionsForEncryptionKey(ctx context.Context, encryptionKeyId apid.ID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteEncryptionKeyVersionsForEncryptionKey", ctx, encryptionKeyId)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteEncryptionKeyVersionsForEncryptionKey indicates an expected call of DeleteEncryptionKeyVersionsForEncryptionKey.
func (mr *MockDBMockRecorder) DeleteEncryptionKeyVersionsForEncryptionKey(ctx, encryptionKeyId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteEncryptionKeyVersionsForEncryptionKey", reflect.TypeOf((*MockDB)(nil).DeleteEncryptionKeyVersionsForEncryptionKey), ctx, encryptionKeyId)
}

// DeleteExpiredNonces mocks base method.
func (m *MockDB) DeleteExpiredNonces(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteExpiredNonces", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteExpiredNonces indicates an expected call of DeleteExpiredNonces.
func (mr *MockDBMockRecorder) DeleteExpiredNonces(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteExpiredNonces", reflect.TypeOf((*MockDB)(nil).DeleteExpiredNonces), ctx)
}

// DeleteNamespace mocks base method.
func (m *MockDB) DeleteNamespace(ctx context.Context, path string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteNamespace", ctx, path)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteNamespace indicates an expected call of DeleteNamespace.
func (mr *MockDBMockRecorder) DeleteNamespace(ctx, path interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteNamespace", reflect.TypeOf((*MockDB)(nil).DeleteNamespace), ctx, path)
}

// DeleteNamespaceAnnotations mocks base method.
func (m *MockDB) DeleteNamespaceAnnotations(ctx context.Context, path string, keys []string) (*database.Namespace, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteNamespaceAnnotations", ctx, path, keys)
	ret0, _ := ret[0].(*database.Namespace)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteNamespaceAnnotations indicates an expected call of DeleteNamespaceAnnotations.
func (mr *MockDBMockRecorder) DeleteNamespaceAnnotations(ctx, path, keys interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteNamespaceAnnotations", reflect.TypeOf((*MockDB)(nil).DeleteNamespaceAnnotations), ctx, path, keys)
}

// DeleteNamespaceLabels mocks base method.
func (m *MockDB) DeleteNamespaceLabels(ctx context.Context, path string, keys []string) (*database.Namespace, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteNamespaceLabels", ctx, path, keys)
	ret0, _ := ret[0].(*database.Namespace)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteNamespaceLabels indicates an expected call of DeleteNamespaceLabels.
func (mr *MockDBMockRecorder) DeleteNamespaceLabels(ctx, path, keys interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteNamespaceLabels", reflect.TypeOf((*MockDB)(nil).DeleteNamespaceLabels), ctx, path, keys)
}

// DeleteOAuth2Token mocks base method.
func (m *MockDB) DeleteOAuth2Token(ctx context.Context, tokenId apid.ID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteOAuth2Token", ctx, tokenId)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteOAuth2Token indicates an expected call of DeleteOAuth2Token.
func (mr *MockDBMockRecorder) DeleteOAuth2Token(ctx, tokenId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteOAuth2Token", reflect.TypeOf((*MockDB)(nil).DeleteOAuth2Token), ctx, tokenId)
}

// EnsureNamespaceByPath mocks base method.
func (m *MockDB) EnsureNamespaceByPath(ctx context.Context, path string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnsureNamespaceByPath", ctx, path)
	ret0, _ := ret[0].(error)
	return ret0
}

// EnsureNamespaceByPath indicates an expected call of EnsureNamespaceByPath.
func (mr *MockDBMockRecorder) EnsureNamespaceByPath(ctx, path interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnsureNamespaceByPath", reflect.TypeOf((*MockDB)(nil).EnsureNamespaceByPath), ctx, path)
}

// EnumerateEncryptionKeyVersionsForKey mocks base method.
func (m *MockDB) EnumerateEncryptionKeyVersionsForKey(ctx context.Context, ekId apid.ID, callback func([]*database.EncryptionKeyVersion, bool) (bool, error)) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnumerateEncryptionKeyVersionsForKey", ctx, ekId, callback)
	ret0, _ := ret[0].(error)
	return ret0
}

// EnumerateEncryptionKeyVersionsForKey indicates an expected call of EnumerateEncryptionKeyVersionsForKey.
func (mr *MockDBMockRecorder) EnumerateEncryptionKeyVersionsForKey(ctx, ekId, callback interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnumerateEncryptionKeyVersionsForKey", reflect.TypeOf((*MockDB)(nil).EnumerateEncryptionKeyVersionsForKey), ctx, ekId, callback)
}

// EnumerateEncryptionKeysInDependencyOrder mocks base method.
func (m *MockDB) EnumerateEncryptionKeysInDependencyOrder(ctx context.Context, callback func([]*database.EncryptionKey, int) (bool, error)) ([]*database.EncryptionKey, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnumerateEncryptionKeysInDependencyOrder", ctx, callback)
	ret0, _ := ret[0].([]*database.EncryptionKey)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EnumerateEncryptionKeysInDependencyOrder indicates an expected call of EnumerateEncryptionKeysInDependencyOrder.
func (mr *MockDBMockRecorder) EnumerateEncryptionKeysInDependencyOrder(ctx, callback interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnumerateEncryptionKeysInDependencyOrder", reflect.TypeOf((*MockDB)(nil).EnumerateEncryptionKeysInDependencyOrder), ctx, callback)
}

// EnumerateFieldsRequiringReEncryption mocks base method.
func (m *MockDB) EnumerateFieldsRequiringReEncryption(ctx context.Context, callback func([]database.ReEncryptionTarget, bool) (bool, error)) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnumerateFieldsRequiringReEncryption", ctx, callback)
	ret0, _ := ret[0].(error)
	return ret0
}

// EnumerateFieldsRequiringReEncryption indicates an expected call of EnumerateFieldsRequiringReEncryption.
func (mr *MockDBMockRecorder) EnumerateFieldsRequiringReEncryption(ctx, callback interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnumerateFieldsRequiringReEncryption", reflect.TypeOf((*MockDB)(nil).EnumerateFieldsRequiringReEncryption), ctx, callback)
}

// EnumerateNamespaceEncryptionTargets mocks base method.
func (m *MockDB) EnumerateNamespaceEncryptionTargets(ctx context.Context, callback func([]database.NamespaceEncryptionTarget, bool) ([]database.NamespaceTargetEncryptionKeyVersionUpdate, bool, error)) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnumerateNamespaceEncryptionTargets", ctx, callback)
	ret0, _ := ret[0].(error)
	return ret0
}

// EnumerateNamespaceEncryptionTargets indicates an expected call of EnumerateNamespaceEncryptionTargets.
func (mr *MockDBMockRecorder) EnumerateNamespaceEncryptionTargets(ctx, callback interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnumerateNamespaceEncryptionTargets", reflect.TypeOf((*MockDB)(nil).EnumerateNamespaceEncryptionTargets), ctx, callback)
}

// EnumerateOAuth2TokensExpiringWithin mocks base method.
func (m *MockDB) EnumerateOAuth2TokensExpiringWithin(ctx context.Context, duration time.Duration, callback func([]*database.OAuth2TokenWithConnection, bool) (bool, error)) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnumerateOAuth2TokensExpiringWithin", ctx, duration, callback)
	ret0, _ := ret[0].(error)
	return ret0
}

// EnumerateOAuth2TokensExpiringWithin indicates an expected call of EnumerateOAuth2TokensExpiringWithin.
func (mr *MockDBMockRecorder) EnumerateOAuth2TokensExpiringWithin(ctx, duration, callback interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnumerateOAuth2TokensExpiringWithin", reflect.TypeOf((*MockDB)(nil).EnumerateOAuth2TokensExpiringWithin), ctx, duration, callback)
}

// GetActor mocks base method.
func (m *MockDB) GetActor(ctx context.Context, id apid.ID) (*database.Actor, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActor", ctx, id)
	ret0, _ := ret[0].(*database.Actor)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetActor indicates an expected call of GetActor.
func (mr *MockDBMockRecorder) GetActor(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActor", reflect.TypeOf((*MockDB)(nil).GetActor), ctx, id)
}

// GetActorByExternalId mocks base method.
func (m *MockDB) GetActorByExternalId(ctx context.Context, namespace, externalId string) (*database.Actor, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActorByExternalId", ctx, namespace, externalId)
	ret0, _ := ret[0].(*database.Actor)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetActorByExternalId indicates an expected call of GetActorByExternalId.
func (mr *MockDBMockRecorder) GetActorByExternalId(ctx, namespace, externalId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActorByExternalId", reflect.TypeOf((*MockDB)(nil).GetActorByExternalId), ctx, namespace, externalId)
}

// GetConnection mocks base method.
func (m *MockDB) GetConnection(ctx context.Context, id apid.ID) (*database.Connection, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetConnection", ctx, id)
	ret0, _ := ret[0].(*database.Connection)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetConnection indicates an expected call of GetConnection.
func (mr *MockDBMockRecorder) GetConnection(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConnection", reflect.TypeOf((*MockDB)(nil).GetConnection), ctx, id)
}

// GetConnectorVersion mocks base method.
func (m *MockDB) GetConnectorVersion(ctx context.Context, id apid.ID, version uint64) (*database.ConnectorVersion, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetConnectorVersion", ctx, id, version)
	ret0, _ := ret[0].(*database.ConnectorVersion)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetConnectorVersion indicates an expected call of GetConnectorVersion.
func (mr *MockDBMockRecorder) GetConnectorVersion(ctx, id, version interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConnectorVersion", reflect.TypeOf((*MockDB)(nil).GetConnectorVersion), ctx, id, version)
}

// GetConnectorVersionForLabels mocks base method.
func (m *MockDB) GetConnectorVersionForLabels(ctx context.Context, labelSelector string) (*database.ConnectorVersion, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetConnectorVersionForLabels", ctx, labelSelector)
	ret0, _ := ret[0].(*database.ConnectorVersion)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetConnectorVersionForLabels indicates an expected call of GetConnectorVersionForLabels.
func (mr *MockDBMockRecorder) GetConnectorVersionForLabels(ctx, labelSelector interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConnectorVersionForLabels", reflect.TypeOf((*MockDB)(nil).GetConnectorVersionForLabels), ctx, labelSelector)
}

// GetConnectorVersionForLabelsAndVersion mocks base method.
func (m *MockDB) GetConnectorVersionForLabelsAndVersion(ctx context.Context, labelSelector string, version uint64) (*database.ConnectorVersion, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetConnectorVersionForLabelsAndVersion", ctx, labelSelector, version)
	ret0, _ := ret[0].(*database.ConnectorVersion)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetConnectorVersionForLabelsAndVersion indicates an expected call of GetConnectorVersionForLabelsAndVersion.
func (mr *MockDBMockRecorder) GetConnectorVersionForLabelsAndVersion(ctx, labelSelector, version interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConnectorVersionForLabelsAndVersion", reflect.TypeOf((*MockDB)(nil).GetConnectorVersionForLabelsAndVersion), ctx, labelSelector, version)
}

// GetConnectorVersionForState mocks base method.
func (m *MockDB) GetConnectorVersionForState(ctx context.Context, id apid.ID, state database.ConnectorVersionState) (*database.ConnectorVersion, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetConnectorVersionForState", ctx, id, state)
	ret0, _ := ret[0].(*database.ConnectorVersion)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetConnectorVersionForState indicates an expected call of GetConnectorVersionForState.
func (mr *MockDBMockRecorder) GetConnectorVersionForState(ctx, id, state interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConnectorVersionForState", reflect.TypeOf((*MockDB)(nil).GetConnectorVersionForState), ctx, id, state)
}

// GetConnectorVersions mocks base method.
func (m *MockDB) GetConnectorVersions(ctx context.Context, requested []database.ConnectorVersionId) (map[database.ConnectorVersionId]*database.ConnectorVersion, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetConnectorVersions", ctx, requested)
	ret0, _ := ret[0].(map[database.ConnectorVersionId]*database.ConnectorVersion)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetConnectorVersions indicates an expected call of GetConnectorVersions.
func (mr *MockDBMockRecorder) GetConnectorVersions(ctx, requested interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConnectorVersions", reflect.TypeOf((*MockDB)(nil).GetConnectorVersions), ctx, requested)
}

// GetCurrentEncryptionKeyVersionForEncryptionKey mocks base method.
func (m *MockDB) GetCurrentEncryptionKeyVersionForEncryptionKey(ctx context.Context, encryptionKeyId apid.ID) (*database.EncryptionKeyVersion, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCurrentEncryptionKeyVersionForEncryptionKey", ctx, encryptionKeyId)
	ret0, _ := ret[0].(*database.EncryptionKeyVersion)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCurrentEncryptionKeyVersionForEncryptionKey indicates an expected call of GetCurrentEncryptionKeyVersionForEncryptionKey.
func (mr *MockDBMockRecorder) GetCurrentEncryptionKeyVersionForEncryptionKey(ctx, encryptionKeyId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCurrentEncryptionKeyVersionForEncryptionKey", reflect.TypeOf((*MockDB)(nil).GetCurrentEncryptionKeyVersionForEncryptionKey), ctx, encryptionKeyId)
}

// GetCurrentEncryptionKeyVersionForNamespace mocks base method.
func (m *MockDB) GetCurrentEncryptionKeyVersionForNamespace(ctx context.Context, namespacePath string) (*database.EncryptionKeyVersion, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCurrentEncryptionKeyVersionForNamespace", ctx, namespacePath)
	ret0, _ := ret[0].(*database.EncryptionKeyVersion)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCurrentEncryptionKeyVersionForNamespace indicates an expected call of GetCurrentEncryptionKeyVersionForNamespace.
func (mr *MockDBMockRecorder) GetCurrentEncryptionKeyVersionForNamespace(ctx, namespacePath interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCurrentEncryptionKeyVersionForNamespace", reflect.TypeOf((*MockDB)(nil).GetCurrentEncryptionKeyVersionForNamespace), ctx, namespacePath)
}

// GetEncryptionKey mocks base method.
func (m *MockDB) GetEncryptionKey(ctx context.Context, id apid.ID) (*database.EncryptionKey, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEncryptionKey", ctx, id)
	ret0, _ := ret[0].(*database.EncryptionKey)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEncryptionKey indicates an expected call of GetEncryptionKey.
func (mr *MockDBMockRecorder) GetEncryptionKey(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEncryptionKey", reflect.TypeOf((*MockDB)(nil).GetEncryptionKey), ctx, id)
}

// GetEncryptionKeyVersion mocks base method.
func (m *MockDB) GetEncryptionKeyVersion(ctx context.Context, id apid.ID) (*database.EncryptionKeyVersion, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEncryptionKeyVersion", ctx, id)
	ret0, _ := ret[0].(*database.EncryptionKeyVersion)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEncryptionKeyVersion indicates an expected call of GetEncryptionKeyVersion.
func (mr *MockDBMockRecorder) GetEncryptionKeyVersion(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEncryptionKeyVersion", reflect.TypeOf((*MockDB)(nil).GetEncryptionKeyVersion), ctx, id)
}

// GetMaxOrderedVersionForEncryptionKey mocks base method.
func (m *MockDB) GetMaxOrderedVersionForEncryptionKey(ctx context.Context, encryptionKeyId apid.ID) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMaxOrderedVersionForEncryptionKey", ctx, encryptionKeyId)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMaxOrderedVersionForEncryptionKey indicates an expected call of GetMaxOrderedVersionForEncryptionKey.
func (mr *MockDBMockRecorder) GetMaxOrderedVersionForEncryptionKey(ctx, encryptionKeyId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMaxOrderedVersionForEncryptionKey", reflect.TypeOf((*MockDB)(nil).GetMaxOrderedVersionForEncryptionKey), ctx, encryptionKeyId)
}

// GetMaxOrderedVersionForNamespace mocks base method.
func (m *MockDB) GetMaxOrderedVersionForNamespace(ctx context.Context, namespacePath string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMaxOrderedVersionForNamespace", ctx, namespacePath)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMaxOrderedVersionForNamespace indicates an expected call of GetMaxOrderedVersionForNamespace.
func (mr *MockDBMockRecorder) GetMaxOrderedVersionForNamespace(ctx, namespacePath interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMaxOrderedVersionForNamespace", reflect.TypeOf((*MockDB)(nil).GetMaxOrderedVersionForNamespace), ctx, namespacePath)
}

// GetNamespace mocks base method.
func (m *MockDB) GetNamespace(ctx context.Context, path string) (*database.Namespace, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNamespace", ctx, path)
	ret0, _ := ret[0].(*database.Namespace)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNamespace indicates an expected call of GetNamespace.
func (mr *MockDBMockRecorder) GetNamespace(ctx, path interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNamespace", reflect.TypeOf((*MockDB)(nil).GetNamespace), ctx, path)
}

// GetOAuth2Token mocks base method.
func (m *MockDB) GetOAuth2Token(ctx context.Context, connectionId apid.ID) (*database.OAuth2Token, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOAuth2Token", ctx, connectionId)
	ret0, _ := ret[0].(*database.OAuth2Token)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOAuth2Token indicates an expected call of GetOAuth2Token.
func (mr *MockDBMockRecorder) GetOAuth2Token(ctx, connectionId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOAuth2Token", reflect.TypeOf((*MockDB)(nil).GetOAuth2Token), ctx, connectionId)
}

// HasNonceBeenUsed mocks base method.
func (m *MockDB) HasNonceBeenUsed(ctx context.Context, nonce apid.ID) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasNonceBeenUsed", ctx, nonce)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HasNonceBeenUsed indicates an expected call of HasNonceBeenUsed.
func (mr *MockDBMockRecorder) HasNonceBeenUsed(ctx, nonce interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasNonceBeenUsed", reflect.TypeOf((*MockDB)(nil).HasNonceBeenUsed), ctx, nonce)
}

// InsertOAuth2Token mocks base method.
func (m *MockDB) InsertOAuth2Token(ctx context.Context, connectionId apid.ID, refreshedFrom *apid.ID, encryptedRefreshToken, encryptedAccessToken encfield.EncryptedField, accessTokenExpiresAt *time.Time, scopes string) (*database.OAuth2Token, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertOAuth2Token", ctx, connectionId, refreshedFrom, encryptedRefreshToken, encryptedAccessToken, accessTokenExpiresAt, scopes)
	ret0, _ := ret[0].(*database.OAuth2Token)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InsertOAuth2Token indicates an expected call of InsertOAuth2Token.
func (mr *MockDBMockRecorder) InsertOAuth2Token(ctx, connectionId, refreshedFrom, encryptedRefreshToken, encryptedAccessToken, accessTokenExpiresAt, scopes interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertOAuth2Token", reflect.TypeOf((*MockDB)(nil).InsertOAuth2Token), ctx, connectionId, refreshedFrom, encryptedRefreshToken, encryptedAccessToken, accessTokenExpiresAt, scopes)
}

// ListActorsBuilder mocks base method.
func (m *MockDB) ListActorsBuilder() database.ListActorsBuilder {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListActorsBuilder")
	ret0, _ := ret[0].(database.ListActorsBuilder)
	return ret0
}

// ListActorsBuilder indicates an expected call of ListActorsBuilder.
func (mr *MockDBMockRecorder) ListActorsBuilder() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListActorsBuilder", reflect.TypeOf((*MockDB)(nil).ListActorsBuilder))
}

// ListActorsFromCursor mocks base method.
func (m *MockDB) ListActorsFromCursor(ctx context.Context, cursor string) (database.ListActorsExecutor, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListActorsFromCursor", ctx, cursor)
	ret0, _ := ret[0].(database.ListActorsExecutor)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListActorsFromCursor indicates an expected call of ListActorsFromCursor.
func (mr *MockDBMockRecorder) ListActorsFromCursor(ctx, cursor interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListActorsFromCursor", reflect.TypeOf((*MockDB)(nil).ListActorsFromCursor), ctx, cursor)
}

// ListConnectionsBuilder mocks base method.
func (m *MockDB) ListConnectionsBuilder() database.ListConnectionsBuilder {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListConnectionsBuilder")
	ret0, _ := ret[0].(database.ListConnectionsBuilder)
	return ret0
}

// ListConnectionsBuilder indicates an expected call of ListConnectionsBuilder.
func (mr *MockDBMockRecorder) ListConnectionsBuilder() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListConnectionsBuilder", reflect.TypeOf((*MockDB)(nil).ListConnectionsBuilder))
}

// ListConnectionsFromCursor mocks base method.
func (m *MockDB) ListConnectionsFromCursor(ctx context.Context, cursor string) (database.ListConnectionsExecutor, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListConnectionsFromCursor", ctx, cursor)
	ret0, _ := ret[0].(database.ListConnectionsExecutor)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListConnectionsFromCursor indicates an expected call of ListConnectionsFromCursor.
func (mr *MockDBMockRecorder) ListConnectionsFromCursor(ctx, cursor interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListConnectionsFromCursor", reflect.TypeOf((*MockDB)(nil).ListConnectionsFromCursor), ctx, cursor)
}

// ListConnectorVersionsBuilder mocks base method.
func (m *MockDB) ListConnectorVersionsBuilder() database.ListConnectorVersionsBuilder {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListConnectorVersionsBuilder")
	ret0, _ := ret[0].(database.ListConnectorVersionsBuilder)
	return ret0
}

// ListConnectorVersionsBuilder indicates an expected call of ListConnectorVersionsBuilder.
func (mr *MockDBMockRecorder) ListConnectorVersionsBuilder() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListConnectorVersionsBuilder", reflect.TypeOf((*MockDB)(nil).ListConnectorVersionsBuilder))
}

// ListConnectorVersionsFromCursor mocks base method.
func (m *MockDB) ListConnectorVersionsFromCursor(ctx context.Context, cursor string) (database.ListConnectorVersionsExecutor, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListConnectorVersionsFromCursor", ctx, cursor)
	ret0, _ := ret[0].(database.ListConnectorVersionsExecutor)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListConnectorVersionsFromCursor indicates an expected call of ListConnectorVersionsFromCursor.
func (mr *MockDBMockRecorder) ListConnectorVersionsFromCursor(ctx, cursor interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListConnectorVersionsFromCursor", reflect.TypeOf((*MockDB)(nil).ListConnectorVersionsFromCursor), ctx, cursor)
}

// ListConnectorsBuilder mocks base method.
func (m *MockDB) ListConnectorsBuilder() database.ListConnectorsBuilder {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListConnectorsBuilder")
	ret0, _ := ret[0].(database.ListConnectorsBuilder)
	return ret0
}

// ListConnectorsBuilder indicates an expected call of ListConnectorsBuilder.
func (mr *MockDBMockRecorder) ListConnectorsBuilder() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListConnectorsBuilder", reflect.TypeOf((*MockDB)(nil).ListConnectorsBuilder))
}

// ListConnectorsFromCursor mocks base method.
func (m *MockDB) ListConnectorsFromCursor(ctx context.Context, cursor string) (database.ListConnectorsExecutor, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListConnectorsFromCursor", ctx, cursor)
	ret0, _ := ret[0].(database.ListConnectorsExecutor)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListConnectorsFromCursor indicates an expected call of ListConnectorsFromCursor.
func (mr *MockDBMockRecorder) ListConnectorsFromCursor(ctx, cursor interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListConnectorsFromCursor", reflect.TypeOf((*MockDB)(nil).ListConnectorsFromCursor), ctx, cursor)
}

// ListEncryptionKeyVersionsForEncryptionKey mocks base method.
func (m *MockDB) ListEncryptionKeyVersionsForEncryptionKey(ctx context.Context, encryptionKeyId apid.ID) ([]*database.EncryptionKeyVersion, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListEncryptionKeyVersionsForEncryptionKey", ctx, encryptionKeyId)
	ret0, _ := ret[0].([]*database.EncryptionKeyVersion)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListEncryptionKeyVersionsForEncryptionKey indicates an expected call of ListEncryptionKeyVersionsForEncryptionKey.
func (mr *MockDBMockRecorder) ListEncryptionKeyVersionsForEncryptionKey(ctx, encryptionKeyId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListEncryptionKeyVersionsForEncryptionKey", reflect.TypeOf((*MockDB)(nil).ListEncryptionKeyVersionsForEncryptionKey), ctx, encryptionKeyId)
}

// ListEncryptionKeyVersionsForNamespace mocks base method.
func (m *MockDB) ListEncryptionKeyVersionsForNamespace(ctx context.Context, namespacePath string) ([]*database.EncryptionKeyVersion, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListEncryptionKeyVersionsForNamespace", ctx, namespacePath)
	ret0, _ := ret[0].([]*database.EncryptionKeyVersion)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListEncryptionKeyVersionsForNamespace indicates an expected call of ListEncryptionKeyVersionsForNamespace.
func (mr *MockDBMockRecorder) ListEncryptionKeyVersionsForNamespace(ctx, namespacePath interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListEncryptionKeyVersionsForNamespace", reflect.TypeOf((*MockDB)(nil).ListEncryptionKeyVersionsForNamespace), ctx, namespacePath)
}

// ListEncryptionKeysBuilder mocks base method.
func (m *MockDB) ListEncryptionKeysBuilder() database.ListEncryptionKeysBuilder {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListEncryptionKeysBuilder")
	ret0, _ := ret[0].(database.ListEncryptionKeysBuilder)
	return ret0
}

// ListEncryptionKeysBuilder indicates an expected call of ListEncryptionKeysBuilder.
func (mr *MockDBMockRecorder) ListEncryptionKeysBuilder() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListEncryptionKeysBuilder", reflect.TypeOf((*MockDB)(nil).ListEncryptionKeysBuilder))
}

// ListEncryptionKeysFromCursor mocks base method.
func (m *MockDB) ListEncryptionKeysFromCursor(ctx context.Context, cursor string) (database.ListEncryptionKeysExecutor, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListEncryptionKeysFromCursor", ctx, cursor)
	ret0, _ := ret[0].(database.ListEncryptionKeysExecutor)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListEncryptionKeysFromCursor indicates an expected call of ListEncryptionKeysFromCursor.
func (mr *MockDBMockRecorder) ListEncryptionKeysFromCursor(ctx, cursor interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListEncryptionKeysFromCursor", reflect.TypeOf((*MockDB)(nil).ListEncryptionKeysFromCursor), ctx, cursor)
}

// ListNamespacesBuilder mocks base method.
func (m *MockDB) ListNamespacesBuilder() database.ListNamespacesBuilder {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListNamespacesBuilder")
	ret0, _ := ret[0].(database.ListNamespacesBuilder)
	return ret0
}

// ListNamespacesBuilder indicates an expected call of ListNamespacesBuilder.
func (mr *MockDBMockRecorder) ListNamespacesBuilder() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListNamespacesBuilder", reflect.TypeOf((*MockDB)(nil).ListNamespacesBuilder))
}

// ListNamespacesFromCursor mocks base method.
func (m *MockDB) ListNamespacesFromCursor(ctx context.Context, cursor string) (database.ListNamespacesExecutor, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListNamespacesFromCursor", ctx, cursor)
	ret0, _ := ret[0].(database.ListNamespacesExecutor)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListNamespacesFromCursor indicates an expected call of ListNamespacesFromCursor.
func (mr *MockDBMockRecorder) ListNamespacesFromCursor(ctx, cursor interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListNamespacesFromCursor", reflect.TypeOf((*MockDB)(nil).ListNamespacesFromCursor), ctx, cursor)
}

// Migrate mocks base method.
func (m *MockDB) Migrate(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Migrate", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Migrate indicates an expected call of Migrate.
func (mr *MockDBMockRecorder) Migrate(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Migrate", reflect.TypeOf((*MockDB)(nil).Migrate), ctx)
}

// NewestConnectorVersionForId mocks base method.
func (m *MockDB) NewestConnectorVersionForId(ctx context.Context, id apid.ID) (*database.ConnectorVersion, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewestConnectorVersionForId", ctx, id)
	ret0, _ := ret[0].(*database.ConnectorVersion)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NewestConnectorVersionForId indicates an expected call of NewestConnectorVersionForId.
func (mr *MockDBMockRecorder) NewestConnectorVersionForId(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewestConnectorVersionForId", reflect.TypeOf((*MockDB)(nil).NewestConnectorVersionForId), ctx, id)
}

// NewestPublishedConnectorVersionForId mocks base method.
func (m *MockDB) NewestPublishedConnectorVersionForId(ctx context.Context, id apid.ID) (*database.ConnectorVersion, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewestPublishedConnectorVersionForId", ctx, id)
	ret0, _ := ret[0].(*database.ConnectorVersion)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NewestPublishedConnectorVersionForId indicates an expected call of NewestPublishedConnectorVersionForId.
func (mr *MockDBMockRecorder) NewestPublishedConnectorVersionForId(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewestPublishedConnectorVersionForId", reflect.TypeOf((*MockDB)(nil).NewestPublishedConnectorVersionForId), ctx, id)
}

// Ping mocks base method.
func (m *MockDB) Ping(ctx context.Context) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ping", ctx)
	ret0, _ := ret[0].(bool)
	return ret0
}

// Ping indicates an expected call of Ping.
func (mr *MockDBMockRecorder) Ping(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ping", reflect.TypeOf((*MockDB)(nil).Ping), ctx)
}

// PurgeSoftDeletedRecords mocks base method.
func (m *MockDB) PurgeSoftDeletedRecords(ctx context.Context, olderThan time.Time) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PurgeSoftDeletedRecords", ctx, olderThan)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PurgeSoftDeletedRecords indicates an expected call of PurgeSoftDeletedRecords.
func (mr *MockDBMockRecorder) PurgeSoftDeletedRecords(ctx, olderThan interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PurgeSoftDeletedRecords", reflect.TypeOf((*MockDB)(nil).PurgeSoftDeletedRecords), ctx, olderThan)
}

// PutActorAnnotations mocks base method.
func (m *MockDB) PutActorAnnotations(ctx context.Context, id apid.ID, annotations map[string]string) (*database.Actor, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PutActorAnnotations", ctx, id, annotations)
	ret0, _ := ret[0].(*database.Actor)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PutActorAnnotations indicates an expected call of PutActorAnnotations.
func (mr *MockDBMockRecorder) PutActorAnnotations(ctx, id, annotations interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PutActorAnnotations", reflect.TypeOf((*MockDB)(nil).PutActorAnnotations), ctx, id, annotations)
}

// PutActorLabels mocks base method.
func (m *MockDB) PutActorLabels(ctx context.Context, id apid.ID, labels map[string]string) (*database.Actor, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PutActorLabels", ctx, id, labels)
	ret0, _ := ret[0].(*database.Actor)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PutActorLabels indicates an expected call of PutActorLabels.
func (mr *MockDBMockRecorder) PutActorLabels(ctx, id, labels interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PutActorLabels", reflect.TypeOf((*MockDB)(nil).PutActorLabels), ctx, id, labels)
}

// PutConnectionAnnotations mocks base method.
func (m *MockDB) PutConnectionAnnotations(ctx context.Context, id apid.ID, annotations map[string]string) (*database.Connection, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PutConnectionAnnotations", ctx, id, annotations)
	ret0, _ := ret[0].(*database.Connection)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PutConnectionAnnotations indicates an expected call of PutConnectionAnnotations.
func (mr *MockDBMockRecorder) PutConnectionAnnotations(ctx, id, annotations interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PutConnectionAnnotations", reflect.TypeOf((*MockDB)(nil).PutConnectionAnnotations), ctx, id, annotations)
}

// PutConnectionLabels mocks base method.
func (m *MockDB) PutConnectionLabels(ctx context.Context, id apid.ID, labels map[string]string) (*database.Connection, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PutConnectionLabels", ctx, id, labels)
	ret0, _ := ret[0].(*database.Connection)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PutConnectionLabels indicates an expected call of PutConnectionLabels.
func (mr *MockDBMockRecorder) PutConnectionLabels(ctx, id, labels interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PutConnectionLabels", reflect.TypeOf((*MockDB)(nil).PutConnectionLabels), ctx, id, labels)
}

// PutEncryptionKeyAnnotations mocks base method.
func (m *MockDB) PutEncryptionKeyAnnotations(ctx context.Context, id apid.ID, annotations map[string]string) (*database.EncryptionKey, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PutEncryptionKeyAnnotations", ctx, id, annotations)
	ret0, _ := ret[0].(*database.EncryptionKey)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PutEncryptionKeyAnnotations indicates an expected call of PutEncryptionKeyAnnotations.
func (mr *MockDBMockRecorder) PutEncryptionKeyAnnotations(ctx, id, annotations interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PutEncryptionKeyAnnotations", reflect.TypeOf((*MockDB)(nil).PutEncryptionKeyAnnotations), ctx, id, annotations)
}

// PutEncryptionKeyLabels mocks base method.
func (m *MockDB) PutEncryptionKeyLabels(ctx context.Context, id apid.ID, labels map[string]string) (*database.EncryptionKey, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PutEncryptionKeyLabels", ctx, id, labels)
	ret0, _ := ret[0].(*database.EncryptionKey)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PutEncryptionKeyLabels indicates an expected call of PutEncryptionKeyLabels.
func (mr *MockDBMockRecorder) PutEncryptionKeyLabels(ctx, id, labels interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PutEncryptionKeyLabels", reflect.TypeOf((*MockDB)(nil).PutEncryptionKeyLabels), ctx, id, labels)
}

// PutNamespaceAnnotations mocks base method.
func (m *MockDB) PutNamespaceAnnotations(ctx context.Context, path string, annotations map[string]string) (*database.Namespace, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PutNamespaceAnnotations", ctx, path, annotations)
	ret0, _ := ret[0].(*database.Namespace)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PutNamespaceAnnotations indicates an expected call of PutNamespaceAnnotations.
func (mr *MockDBMockRecorder) PutNamespaceAnnotations(ctx, path, annotations interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PutNamespaceAnnotations", reflect.TypeOf((*MockDB)(nil).PutNamespaceAnnotations), ctx, path, annotations)
}

// PutNamespaceLabels mocks base method.
func (m *MockDB) PutNamespaceLabels(ctx context.Context, path string, labels map[string]string) (*database.Namespace, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PutNamespaceLabels", ctx, path, labels)
	ret0, _ := ret[0].(*database.Namespace)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PutNamespaceLabels indicates an expected call of PutNamespaceLabels.
func (mr *MockDBMockRecorder) PutNamespaceLabels(ctx, path, labels interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PutNamespaceLabels", reflect.TypeOf((*MockDB)(nil).PutNamespaceLabels), ctx, path, labels)
}

// SetConnectionEncryptedConfiguration mocks base method.
func (m *MockDB) SetConnectionEncryptedConfiguration(ctx context.Context, id apid.ID, encryptedConfig *encfield.EncryptedField) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetConnectionEncryptedConfiguration", ctx, id, encryptedConfig)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetConnectionEncryptedConfiguration indicates an expected call of SetConnectionEncryptedConfiguration.
func (mr *MockDBMockRecorder) SetConnectionEncryptedConfiguration(ctx, id, encryptedConfig interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetConnectionEncryptedConfiguration", reflect.TypeOf((*MockDB)(nil).SetConnectionEncryptedConfiguration), ctx, id, encryptedConfig)
}

// SetConnectionSetupStep mocks base method.
func (m *MockDB) SetConnectionSetupStep(ctx context.Context, id apid.ID, setupStep *string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetConnectionSetupStep", ctx, id, setupStep)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetConnectionSetupStep indicates an expected call of SetConnectionSetupStep.
func (mr *MockDBMockRecorder) SetConnectionSetupStep(ctx, id, setupStep interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetConnectionSetupStep", reflect.TypeOf((*MockDB)(nil).SetConnectionSetupStep), ctx, id, setupStep)
}

// SetConnectionState mocks base method.
func (m *MockDB) SetConnectionState(ctx context.Context, id apid.ID, state database.ConnectionState) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetConnectionState", ctx, id, state)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetConnectionState indicates an expected call of SetConnectionState.
func (mr *MockDBMockRecorder) SetConnectionState(ctx, id, state interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetConnectionState", reflect.TypeOf((*MockDB)(nil).SetConnectionState), ctx, id, state)
}

// SetConnectorVersionState mocks base method.
func (m *MockDB) SetConnectorVersionState(ctx context.Context, id apid.ID, version uint64, state database.ConnectorVersionState) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetConnectorVersionState", ctx, id, version, state)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetConnectorVersionState indicates an expected call of SetConnectorVersionState.
func (mr *MockDBMockRecorder) SetConnectorVersionState(ctx, id, version, state interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetConnectorVersionState", reflect.TypeOf((*MockDB)(nil).SetConnectorVersionState), ctx, id, version, state)
}

// SetCursorEncryptor mocks base method.
func (m *MockDB) SetCursorEncryptor(e pagination.CursorEncryptor) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetCursorEncryptor", e)
}

// SetCursorEncryptor indicates an expected call of SetCursorEncryptor.
func (mr *MockDBMockRecorder) SetCursorEncryptor(e interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetCursorEncryptor", reflect.TypeOf((*MockDB)(nil).SetCursorEncryptor), e)
}

// SetEncryptionKeyState mocks base method.
func (m *MockDB) SetEncryptionKeyState(ctx context.Context, id apid.ID, state database.EncryptionKeyState) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetEncryptionKeyState", ctx, id, state)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetEncryptionKeyState indicates an expected call of SetEncryptionKeyState.
func (mr *MockDBMockRecorder) SetEncryptionKeyState(ctx, id, state interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetEncryptionKeyState", reflect.TypeOf((*MockDB)(nil).SetEncryptionKeyState), ctx, id, state)
}

// SetEncryptionKeyVersionCurrentFlag mocks base method.
func (m *MockDB) SetEncryptionKeyVersionCurrentFlag(ctx context.Context, id apid.ID, isCurrent bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetEncryptionKeyVersionCurrentFlag", ctx, id, isCurrent)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetEncryptionKeyVersionCurrentFlag indicates an expected call of SetEncryptionKeyVersionCurrentFlag.
func (mr *MockDBMockRecorder) SetEncryptionKeyVersionCurrentFlag(ctx, id, isCurrent interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetEncryptionKeyVersionCurrentFlag", reflect.TypeOf((*MockDB)(nil).SetEncryptionKeyVersionCurrentFlag), ctx, id, isCurrent)
}

// SetNamespaceEncryptionKeyId mocks base method.
func (m *MockDB) SetNamespaceEncryptionKeyId(ctx context.Context, path string, ekId *apid.ID) (*database.Namespace, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetNamespaceEncryptionKeyId", ctx, path, ekId)
	ret0, _ := ret[0].(*database.Namespace)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetNamespaceEncryptionKeyId indicates an expected call of SetNamespaceEncryptionKeyId.
func (mr *MockDBMockRecorder) SetNamespaceEncryptionKeyId(ctx, path, ekId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetNamespaceEncryptionKeyId", reflect.TypeOf((*MockDB)(nil).SetNamespaceEncryptionKeyId), ctx, path, ekId)
}

// SetNamespaceState mocks base method.
func (m *MockDB) SetNamespaceState(ctx context.Context, path string, state database.NamespaceState) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetNamespaceState", ctx, path, state)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetNamespaceState indicates an expected call of SetNamespaceState.
func (mr *MockDBMockRecorder) SetNamespaceState(ctx, path, state interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetNamespaceState", reflect.TypeOf((*MockDB)(nil).SetNamespaceState), ctx, path, state)
}

// UpdateActorAnnotations mocks base method.
func (m *MockDB) UpdateActorAnnotations(ctx context.Context, id apid.ID, annotations map[string]string) (*database.Actor, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateActorAnnotations", ctx, id, annotations)
	ret0, _ := ret[0].(*database.Actor)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateActorAnnotations indicates an expected call of UpdateActorAnnotations.
func (mr *MockDBMockRecorder) UpdateActorAnnotations(ctx, id, annotations interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateActorAnnotations", reflect.TypeOf((*MockDB)(nil).UpdateActorAnnotations), ctx, id, annotations)
}

// UpdateConnectionAnnotations mocks base method.
func (m *MockDB) UpdateConnectionAnnotations(ctx context.Context, id apid.ID, annotations map[string]string) (*database.Connection, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateConnectionAnnotations", ctx, id, annotations)
	ret0, _ := ret[0].(*database.Connection)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateConnectionAnnotations indicates an expected call of UpdateConnectionAnnotations.
func (mr *MockDBMockRecorder) UpdateConnectionAnnotations(ctx, id, annotations interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateConnectionAnnotations", reflect.TypeOf((*MockDB)(nil).UpdateConnectionAnnotations), ctx, id, annotations)
}

// UpdateConnectionLabels mocks base method.
func (m *MockDB) UpdateConnectionLabels(ctx context.Context, id apid.ID, labels map[string]string) (*database.Connection, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateConnectionLabels", ctx, id, labels)
	ret0, _ := ret[0].(*database.Connection)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateConnectionLabels indicates an expected call of UpdateConnectionLabels.
func (mr *MockDBMockRecorder) UpdateConnectionLabels(ctx, id, labels interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateConnectionLabels", reflect.TypeOf((*MockDB)(nil).UpdateConnectionLabels), ctx, id, labels)
}

// UpdateEncryptionKey mocks base method.
func (m *MockDB) UpdateEncryptionKey(ctx context.Context, id apid.ID, updates map[string]interface{}) (*database.EncryptionKey, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateEncryptionKey", ctx, id, updates)
	ret0, _ := ret[0].(*database.EncryptionKey)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateEncryptionKey indicates an expected call of UpdateEncryptionKey.
func (mr *MockDBMockRecorder) UpdateEncryptionKey(ctx, id, updates interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateEncryptionKey", reflect.TypeOf((*MockDB)(nil).UpdateEncryptionKey), ctx, id, updates)
}

// UpdateEncryptionKeyAnnotations mocks base method.
func (m *MockDB) UpdateEncryptionKeyAnnotations(ctx context.Context, id apid.ID, annotations map[string]string) (*database.EncryptionKey, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateEncryptionKeyAnnotations", ctx, id, annotations)
	ret0, _ := ret[0].(*database.EncryptionKey)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateEncryptionKeyAnnotations indicates an expected call of UpdateEncryptionKeyAnnotations.
func (mr *MockDBMockRecorder) UpdateEncryptionKeyAnnotations(ctx, id, annotations interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateEncryptionKeyAnnotations", reflect.TypeOf((*MockDB)(nil).UpdateEncryptionKeyAnnotations), ctx, id, annotations)
}

// UpdateEncryptionKeyLabels mocks base method.
func (m *MockDB) UpdateEncryptionKeyLabels(ctx context.Context, id apid.ID, labels map[string]string) (*database.EncryptionKey, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateEncryptionKeyLabels", ctx, id, labels)
	ret0, _ := ret[0].(*database.EncryptionKey)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateEncryptionKeyLabels indicates an expected call of UpdateEncryptionKeyLabels.
func (mr *MockDBMockRecorder) UpdateEncryptionKeyLabels(ctx, id, labels interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateEncryptionKeyLabels", reflect.TypeOf((*MockDB)(nil).UpdateEncryptionKeyLabels), ctx, id, labels)
}

// UpdateNamespaceAnnotations mocks base method.
func (m *MockDB) UpdateNamespaceAnnotations(ctx context.Context, path string, annotations map[string]string) (*database.Namespace, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateNamespaceAnnotations", ctx, path, annotations)
	ret0, _ := ret[0].(*database.Namespace)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateNamespaceAnnotations indicates an expected call of UpdateNamespaceAnnotations.
func (mr *MockDBMockRecorder) UpdateNamespaceAnnotations(ctx, path, annotations interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateNamespaceAnnotations", reflect.TypeOf((*MockDB)(nil).UpdateNamespaceAnnotations), ctx, path, annotations)
}

// UpdateNamespaceLabels mocks base method.
func (m *MockDB) UpdateNamespaceLabels(ctx context.Context, path string, labels map[string]string) (*database.Namespace, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateNamespaceLabels", ctx, path, labels)
	ret0, _ := ret[0].(*database.Namespace)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateNamespaceLabels indicates an expected call of UpdateNamespaceLabels.
func (mr *MockDBMockRecorder) UpdateNamespaceLabels(ctx, path, labels interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateNamespaceLabels", reflect.TypeOf((*MockDB)(nil).UpdateNamespaceLabels), ctx, path, labels)
}

// UpsertActor mocks base method.
func (m *MockDB) UpsertActor(ctx context.Context, actor database.IActorData) (*database.Actor, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertActor", ctx, actor)
	ret0, _ := ret[0].(*database.Actor)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpsertActor indicates an expected call of UpsertActor.
func (mr *MockDBMockRecorder) UpsertActor(ctx, actor interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertActor", reflect.TypeOf((*MockDB)(nil).UpsertActor), ctx, actor)
}

// UpsertConnectorVersion mocks base method.
func (m *MockDB) UpsertConnectorVersion(ctx context.Context, cv *database.ConnectorVersion) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertConnectorVersion", ctx, cv)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertConnectorVersion indicates an expected call of UpsertConnectorVersion.
func (mr *MockDBMockRecorder) UpsertConnectorVersion(ctx, cv interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertConnectorVersion", reflect.TypeOf((*MockDB)(nil).UpsertConnectorVersion), ctx, cv)
}
