// Code generated by MockGen. DO NOT EDIT.
// Source: ./interface.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	apid "github.com/rmorlok/authproxy/internal/apid"
	encfield "github.com/rmorlok/authproxy/internal/encfield"
	encrypt "github.com/rmorlok/authproxy/internal/encrypt"
)

// MockNamespacedEntity is a mock of NamespacedEntity interface.
type MockNamespacedEntity struct {
	ctrl     *gomock.Controller
	recorder *MockNamespacedEntityMockRecorder
}

// MockNamespacedEntityMockRecorder is the mock recorder for MockNamespacedEntity.
type MockNamespacedEntityMockRecorder struct {
	mock *MockNamespacedEntity
}

// NewMockNamespacedEntity creates a new mock instance.
func NewMockNamespacedEntity(ctrl *gomock.Controller) *MockNamespacedEntity {
	mock := &MockNamespacedEntity{ctrl: ctrl}
	mock.recorder = &MockNamespacedEntityMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNamespacedEntity) EXPECT() *MockNamespacedEntityMockRecorder {
	return m.recorder
}

// GetNamespace mocks base method.
func (m *MockNamespacedEntity) GetNamespace() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNamespace")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetNamespace indicates an expected call of GetNamespace.
func (mr *MockNamespacedEntityMockRecorder) GetNamespace() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNamespace", reflect.TypeOf((*MockNamespacedEntity)(nil).GetNamespace))
}

// MockE is a mock of E interface.
type MockE struct {
	ctrl     *gomock.Controller
	recorder *MockEMockRecorder
}

// MockEMockRecorder is the mock recorder for MockE.
type MockEMockRecorder struct {
	mock *MockE
}

// NewMockE creates a new mock instance.
func NewMockE(ctrl *gomock.Controller) *MockE {
	mock := &MockE{ctrl: ctrl}
	mock.recorder = &MockEMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockE) EXPECT() *MockEMockRecorder {
	return m.recorder
}

// Decrypt mocks base method.
func (m *MockE) Decrypt(ctx context.Context, ef encfield.EncryptedField) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Decrypt", ctx, ef)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Decrypt indicates an expected call of Decrypt.
func (mr *MockEMockRecorder) Decrypt(ctx, ef interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Decrypt", reflect.TypeOf((*MockE)(nil).Decrypt), ctx, ef)
}

// DecryptString mocks base method.
func (m *MockE) DecryptString(ctx context.Context, ef encfield.EncryptedField) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DecryptString", ctx, ef)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DecryptString indicates an expected call of DecryptString.
func (mr *MockEMockRecorder) DecryptString(ctx, ef interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DecryptString", reflect.TypeOf((*MockE)(nil).DecryptString), ctx, ef)
}

// EncryptForEntity mocks base method.
func (m *MockE) EncryptForEntity(ctx context.Context, entity encrypt.NamespacedEntity, data []byte) (encfield.EncryptedField, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EncryptForEntity", ctx, entity, data)
	ret0, _ := ret[0].(encfield.EncryptedField)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EncryptForEntity indicates an expected call of EncryptForEntity.
func (mr *MockEMockRecorder) EncryptForEntity(ctx, entity, data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EncryptForEntity", reflect.TypeOf((*MockE)(nil).EncryptForEntity), ctx, entity, data)
}

// EncryptForKey mocks base method.
func (m *MockE) EncryptForKey(ctx context.Context, keyId apid.ID, data []byte) (encfield.EncryptedField, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EncryptForKey", ctx, keyId, data)
	ret0, _ := ret[0].(encfield.EncryptedField)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EncryptForKey indicates an expected call of EncryptForKey.
func (mr *MockEMockRecorder) EncryptForKey(ctx, keyId, data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EncryptForKey", reflect.TypeOf((*MockE)(nil).EncryptForKey), ctx, keyId, data)
}

// EncryptForNamespace mocks base method.
func (m *MockE) EncryptForNamespace(ctx context.Context, namespacePath string, data []byte) (encfield.EncryptedField, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EncryptForNamespace", ctx, namespacePath, data)
	ret0, _ := ret[0].(encfield.EncryptedField)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EncryptForNamespace indicates an expected call of EncryptForNamespace.
func (mr *MockEMockRecorder) EncryptForNamespace(ctx, namespacePath, data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EncryptForNamespace", reflect.TypeOf((*MockE)(nil).EncryptForNamespace), ctx, namespacePath, data)
}

// EncryptGlobal mocks base method.
func (m *MockE) EncryptGlobal(ctx context.Context, data []byte) (encfield.EncryptedField, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EncryptGlobal", ctx, data)
	ret0, _ := ret[0].(encfield.EncryptedField)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EncryptGlobal indicates an expected call of EncryptGlobal.
func (mr *MockEMockRecorder) EncryptGlobal(ctx, data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EncryptGlobal", reflect.TypeOf((*MockE)(nil).EncryptGlobal), ctx, data)
}

// EncryptStringForEntity mocks base method.
func (m *MockE) EncryptStringForEntity(ctx context.Context, enity encrypt.NamespacedEntity, data string) (encfield.EncryptedField, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EncryptStringForEntity", ctx, enity, data)
	ret0, _ := ret[0].(encfield.EncryptedField)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EncryptStringForEntity indicates an expected call of EncryptStringForEntity.
func (mr *MockEMockRecorder) EncryptStringForEntity(ctx, enity, data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EncryptStringForEntity", reflect.TypeOf((*MockE)(nil).EncryptStringForEntity), ctx, enity, data)
}

// EncryptStringForKey mocks base method.
func (m *MockE) EncryptStringForKey(ctx context.Context, keyId apid.ID, data string) (encfield.EncryptedField, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EncryptStringForKey", ctx, keyId, data)
	ret0, _ := ret[0].(encfield.EncryptedField)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EncryptStringForKey indicates an expected call of EncryptStringForKey.
func (mr *MockEMockRecorder) EncryptStringForKey(ctx, keyId, data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EncryptStringForKey", reflect.TypeOf((*MockE)(nil).EncryptStringForKey), ctx, keyId, data)
}

// EncryptStringForNamespace mocks base method.
func (m *MockE) EncryptStringForNamespace(ctx context.Context, namespacePath, data string) (encfield.EncryptedField, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EncryptStringForNamespace", ctx, namespacePath, data)
	ret0, _ := ret[0].(encfield.EncryptedField)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EncryptStringForNamespace indicates an expected call of EncryptStringForNamespace.
func (mr *MockEMockRecorder) EncryptStringForNamespace(ctx, namespacePath, data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EncryptStringForNamespace", reflect.TypeOf((*MockE)(nil).EncryptStringForNamespace), ctx, namespacePath, data)
}

// EncryptStringGlobal mocks base method.
func (m *MockE) EncryptStringGlobal(ctx context.Context, data string) (encfield.EncryptedField, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EncryptStringGlobal", ctx, data)
	ret0, _ := ret[0].(encfield.EncryptedField)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EncryptStringGlobal indicates an expected call of EncryptStringGlobal.
func (mr *MockEMockRecorder) EncryptStringGlobal(ctx, data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EncryptStringGlobal", reflect.TypeOf((*MockE)(nil).EncryptStringGlobal), ctx, data)
}

// ReEncryptField mocks base method.
func (m *MockE) ReEncryptField(ctx context.Context, ef encfield.EncryptedField, targetEkvId apid.ID) (encfield.EncryptedField, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReEncryptField", ctx, ef, targetEkvId)
	ret0, _ := ret[0].(encfield.EncryptedField)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReEncryptField indicates an expected call of ReEncryptField.
func (mr *MockEMockRecorder) ReEncryptField(ctx, ef, targetEkvId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReEncryptField", reflect.TypeOf((*MockE)(nil).ReEncryptField), ctx, ef, targetEkvId)
}

// Shutdown mocks base method.
func (m *MockE) Shutdown() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Shutdown")
}

// Shutdown indicates an expected call of Shutdown.
func (mr *MockEMockRecorder) Shutdown() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Shutdown", reflect.TypeOf((*MockE)(nil).Shutdown))
}

// Start mocks base method.
func (m *MockE) Start() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Start")
}

// Start indicates an expected call of Start.
func (mr *MockEMockRecorder) Start() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockE)(nil).Start))
}

// SyncKeysFromDbToMemory mocks base method.
func (m *MockE) SyncKeysFromDbToMemory(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SyncKeysFromDbToMemory", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// SyncKeysFromDbToMemory indicates an expected call of SyncKeysFromDbToMemory.
func (mr *MockEMockRecorder) SyncKeysFromDbToMemory(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SyncKeysFromDbToMemory", reflect.TypeOf((*MockE)(nil).SyncKeysFromDbToMemory), ctx)
}
