// Code generated by MockGen. DO NOT EDIT.
// Source: ./interface.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	apid "github.com/rmorlok/authproxy/internal/apid"
	encrypt "github.com/rmorlok/authproxy/internal/encrypt"
)

// MockConnectorVersion is a mock of ConnectorVersion interface.
type MockConnectorVersion struct {
	ctrl     *gomock.Controller
	recorder *MockConnectorVersionMockRecorder
}

// MockConnectorVersionMockRecorder is the mock recorder for MockConnectorVersion.
type MockConnectorVersionMockRecorder struct {
	mock *MockConnectorVersion
}

// NewMockConnectorVersion creates a new mock instance.
func NewMockConnectorVersion(ctrl *gomock.Controller) *MockConnectorVersion {
	mock := &MockConnectorVersion{ctrl: ctrl}
	mock.recorder = &MockConnectorVersionMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConnectorVersion) EXPECT() *MockConnectorVersionMockRecorder {
	return m.recorder
}

// GetId mocks base method.
func (m *MockConnectorVersion) GetId() apid.ID {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetId")
	ret0, _ := ret[0].(apid.ID)
	return ret0
}

// GetId indicates an expected call of GetId.
func (mr *MockConnectorVersionMockRecorder) GetId() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetId", reflect.TypeOf((*MockConnectorVersion)(nil).GetId))
}

// GetNamespace mocks base method.
func (m *MockConnectorVersion) GetNamespace() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNamespace")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetNamespace indicates an expected call of GetNamespace.
func (mr *MockConnectorVersionMockRecorder) GetNamespace() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNamespace", reflect.TypeOf((*MockConnectorVersion)(nil).GetNamespace))
}

// GetVersion mocks base method.
func (m *MockConnectorVersion) GetVersion() uint64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetVersion")
	ret0, _ := ret[0].(uint64)
	return ret0
}

// GetVersion indicates an expected call of GetVersion.
func (mr *MockConnectorVersionMockRecorder) GetVersion() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetVersion", reflect.TypeOf((*MockConnectorVersion)(nil).GetVersion))
}

// MockConnection is a mock of Connection interface.
type MockConnection struct {
	ctrl     *gomock.Controller
	recorder *MockConnectionMockRecorder
}

// MockConnectionMockRecorder is the mock recorder for MockConnection.
type MockConnectionMockRecorder struct {
	mock *MockConnection
}

// NewMockConnection creates a new mock instance.
func NewMockConnection(ctrl *gomock.Controller) *MockConnection {
	mock := &MockConnection{ctrl: ctrl}
	mock.recorder = &MockConnectionMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConnection) EXPECT() *MockConnectionMockRecorder {
	return m.recorder
}

// GetConnectorId mocks base method.
func (m *MockConnection) GetConnectorId() apid.ID {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetConnectorId")
	ret0, _ := ret[0].(apid.ID)
	return ret0
}

// GetConnectorId indicates an expected call of GetConnectorId.
func (mr *MockConnectionMockRecorder) GetConnectorId() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConnectorId", reflect.TypeOf((*MockConnection)(nil).GetConnectorId))
}

// GetConnectorVersion mocks base method.
func (m *MockConnection) GetConnectorVersion() uint64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetConnectorVersion")
	ret0, _ := ret[0].(uint64)
	return ret0
}

// GetConnectorVersion indicates an expected call of GetConnectorVersion.
func (mr *MockConnectionMockRecorder) GetConnectorVersion() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConnectorVersion", reflect.TypeOf((*MockConnection)(nil).GetConnectorVersion))
}

// GetId mocks base method.
func (m *MockConnection) GetId() apid.ID {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetId")
	ret0, _ := ret[0].(apid.ID)
	return ret0
}

// GetId indicates an expected call of GetId.
func (mr *MockConnectionMockRecorder) GetId() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetId", reflect.TypeOf((*MockConnection)(nil).GetId))
}

// GetNamespace mocks base method.
func (m *MockConnection) GetNamespace() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNamespace")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetNamespace indicates an expected call of GetNamespace.
func (mr *MockConnectionMockRecorder) GetNamespace() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNamespace", reflect.TypeOf((*MockConnection)(nil).GetNamespace))
}

// MockE is a mock of E interface.
type MockE struct {
	ctrl     *gomock.Controller
	recorder *MockEMockRecorder
}

// MockEMockRecorder is the mock recorder for MockE.
type MockEMockRecorder struct {
	mock *MockE
}

// NewMockE creates a new mock instance.
func NewMockE(ctrl *gomock.Controller) *MockE {
	mock := &MockE{ctrl: ctrl}
	mock.recorder = &MockEMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockE) EXPECT() *MockEMockRecorder {
	return m.recorder
}

// DecryptForConnection mocks base method.
func (m *MockE) DecryptForConnection(ctx context.Context, connection encrypt.Connection, data []byte) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DecryptForConnection", ctx, connection, data)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DecryptForConnection indicates an expected call of DecryptForConnection.
func (mr *MockEMockRecorder) DecryptForConnection(ctx, connection, data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DecryptForConnection", reflect.TypeOf((*MockE)(nil).DecryptForConnection), ctx, connection, data)
}

// DecryptForConnector mocks base method.
func (m *MockE) DecryptForConnector(ctx context.Context, connection encrypt.ConnectorVersion, data []byte) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DecryptForConnector", ctx, connection, data)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DecryptForConnector indicates an expected call of DecryptForConnector.
func (mr *MockEMockRecorder) DecryptForConnector(ctx, connection, data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DecryptForConnector", reflect.TypeOf((*MockE)(nil).DecryptForConnector), ctx, connection, data)
}

// DecryptGlobal mocks base method.
func (m *MockE) DecryptGlobal(ctx context.Context, data []byte) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DecryptGlobal", ctx, data)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DecryptGlobal indicates an expected call of DecryptGlobal.
func (mr *MockEMockRecorder) DecryptGlobal(ctx, data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DecryptGlobal", reflect.TypeOf((*MockE)(nil).DecryptGlobal), ctx, data)
}

// DecryptStringForConnection mocks base method.
func (m *MockE) DecryptStringForConnection(ctx context.Context, connection encrypt.Connection, base64 string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DecryptStringForConnection", ctx, connection, base64)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DecryptStringForConnection indicates an expected call of DecryptStringForConnection.
func (mr *MockEMockRecorder) DecryptStringForConnection(ctx, connection, base64 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DecryptStringForConnection", reflect.TypeOf((*MockE)(nil).DecryptStringForConnection), ctx, connection, base64)
}

// DecryptStringForConnector mocks base method.
func (m *MockE) DecryptStringForConnector(ctx context.Context, connection encrypt.ConnectorVersion, base64 string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DecryptStringForConnector", ctx, connection, base64)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DecryptStringForConnector indicates an expected call of DecryptStringForConnector.
func (mr *MockEMockRecorder) DecryptStringForConnector(ctx, connection, base64 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DecryptStringForConnector", reflect.TypeOf((*MockE)(nil).DecryptStringForConnector), ctx, connection, base64)
}

// DecryptStringGlobal mocks base method.
func (m *MockE) DecryptStringGlobal(ctx context.Context, base64 string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DecryptStringGlobal", ctx, base64)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DecryptStringGlobal indicates an expected call of DecryptStringGlobal.
func (mr *MockEMockRecorder) DecryptStringGlobal(ctx, base64 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DecryptStringGlobal", reflect.TypeOf((*MockE)(nil).DecryptStringGlobal), ctx, base64)
}

// EncryptForConnection mocks base method.
func (m *MockE) EncryptForConnection(ctx context.Context, connection encrypt.Connection, data []byte) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EncryptForConnection", ctx, connection, data)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EncryptForConnection indicates an expected call of EncryptForConnection.
func (mr *MockEMockRecorder) EncryptForConnection(ctx, connection, data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EncryptForConnection", reflect.TypeOf((*MockE)(nil).EncryptForConnection), ctx, connection, data)
}

// EncryptForConnector mocks base method.
func (m *MockE) EncryptForConnector(ctx context.Context, connection encrypt.ConnectorVersion, data []byte) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EncryptForConnector", ctx, connection, data)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EncryptForConnector indicates an expected call of EncryptForConnector.
func (mr *MockEMockRecorder) EncryptForConnector(ctx, connection, data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EncryptForConnector", reflect.TypeOf((*MockE)(nil).EncryptForConnector), ctx, connection, data)
}

// EncryptGlobal mocks base method.
func (m *MockE) EncryptGlobal(ctx context.Context, data []byte) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EncryptGlobal", ctx, data)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EncryptGlobal indicates an expected call of EncryptGlobal.
func (mr *MockEMockRecorder) EncryptGlobal(ctx, data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EncryptGlobal", reflect.TypeOf((*MockE)(nil).EncryptGlobal), ctx, data)
}

// EncryptStringForConnection mocks base method.
func (m *MockE) EncryptStringForConnection(ctx context.Context, connection encrypt.Connection, data string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EncryptStringForConnection", ctx, connection, data)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EncryptStringForConnection indicates an expected call of EncryptStringForConnection.
func (mr *MockEMockRecorder) EncryptStringForConnection(ctx, connection, data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EncryptStringForConnection", reflect.TypeOf((*MockE)(nil).EncryptStringForConnection), ctx, connection, data)
}

// EncryptStringForConnector mocks base method.
func (m *MockE) EncryptStringForConnector(ctx context.Context, connection encrypt.ConnectorVersion, data string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EncryptStringForConnector", ctx, connection, data)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EncryptStringForConnector indicates an expected call of EncryptStringForConnector.
func (mr *MockEMockRecorder) EncryptStringForConnector(ctx, connection, data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EncryptStringForConnector", reflect.TypeOf((*MockE)(nil).EncryptStringForConnector), ctx, connection, data)
}

// EncryptStringGlobal mocks base method.
func (m *MockE) EncryptStringGlobal(ctx context.Context, data string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EncryptStringGlobal", ctx, data)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EncryptStringGlobal indicates an expected call of EncryptStringGlobal.
func (mr *MockEMockRecorder) EncryptStringGlobal(ctx, data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EncryptStringGlobal", reflect.TypeOf((*MockE)(nil).EncryptStringGlobal), ctx, data)
}

// IsEncryptedWithPrimaryKey mocks base method.
func (m *MockE) IsEncryptedWithPrimaryKey(base64Str string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsEncryptedWithPrimaryKey", base64Str)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsEncryptedWithPrimaryKey indicates an expected call of IsEncryptedWithPrimaryKey.
func (mr *MockEMockRecorder) IsEncryptedWithPrimaryKey(base64Str interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsEncryptedWithPrimaryKey", reflect.TypeOf((*MockE)(nil).IsEncryptedWithPrimaryKey), base64Str)
}
