apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: demo
namePrefix: demo-

resources:
  - seed-config.yaml
  - seed-job.yaml

images:
  - name: ghcr.io/rmorlok/authproxy-demo-seed
    newTag: main

labels:
  - pairs:
      app.kubernetes.io/part-of: authproxy-demo
